### ISSUE TITLE
black gnome terminal has no border

### ISSUE THREAD

**Issue by drakkan** [pop-os/gtk-theme#101]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - archlinux
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - Gnome
 * Pop version - 3.0.0-b4
 ```

**Related Application and/or Shell theming (or name of widget)**

gnome-terminal

**Actual issue**

Overlapping a black gnome terminal over another means, that no border is visible

**Steps to reproduce**

overlap a black gnome terminal on another

**Expected behavior**

gnome terminal should have a border

**Other Note (feature-request, question, etc...)**

please look at these related links

https://bbs.archlinux.org/viewtopic.php?id=196200
https://github.com/numixproject/numix-gtk-theme/issues/287

**Comment by isantop** [comment]
Thanks for your report! Luckily Terminal is easy to special-case and a border is pretty easy (without requiring borders on every window). Fixed in 9caa8f678df64ad4fee5bbf902c611fef43a61d0 of the `version-3` branch, and will be available in the next beta of version 3.

**Comment by isantop** [comment]
![screenshot from 2017-12-14 10-59-15](https://user-images.githubusercontent.com/5883565/34007104-dea2b92e-e0bd-11e7-8114-99ccaf92a1df.png)

**Comment by drakkan** [comment]
great! thanks

**Comment by megies** [comment]
This also affects current Debian Stretch. Am I right in assuming that this can not easily be monkey patched in a live system because everything's compiled?

**Comment by isantop** [comment]
@megies Are you using the Pop theme? If so, updating should bring this fix in for you. Any revision of Version 3 of the theme should have the fix for this applied. 

If you're not using the Pop theme I'm afraid there isn't anything I could do for this.

**Comment by megies** [comment]
Uhm, no idea how to tell which theme I'm on, it's just a stock Debian Stretch with gnome 3.22.2. Debian won't package an update for this, I don't think so (they're mostly doing security patches). Anyway thanks for taking the time to answer.

**Comment by isantop** [comment]
@megies Yeah, Debian does not currently use or Package the Pop Theme (to my knowledge; if they do, awesome!). For your problem I suggest filing an Issue with the [Debian Bug Tracking System](https://www.debian.org/Bugs/). There's a good guide for how to do that available [here](https://www.debian.org/Bugs/)

**Comment by megies** [comment]
Uhm, I actually only noticed right now that this is the repo of a theme and not main gnome.. sorry for having bothered you about this, google sent me here searching for this issue. And the description matched exactly..

**Comment by drakkan** [comment]
this happens again in version 5.0.0
