### ISSUE TITLE
Close button not showing when hovering windows in activities overview in dark variants of the GNOME Shell theme

### ISSUE THREAD

**Issue by vascocosta** [pop-os/gtk-theme#108]
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

* Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
```
libgtk-3-0:
  Installed: 3.22.25-0ubuntu0.1
  Candidate: 3.22.25-0ubuntu0.1
  Version table:
 *** 3.22.25-0ubuntu0.1 500
        500 http://pt.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.22.24-0ubuntu1 500
        500 http://pt.archive.ubuntu.com/ubuntu artful/main amd64 Packages
```

 * Desktop environment - 
```
GNOME 3
```

 * Pop version - (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```)
```
/***************************
 * Pop!_GTK+ Version 3.0.0 *
 ***************************/
```

**Actual issue**

Close button not showing when hovering windows in activities overview in dark variants of the GNOME Shell theme. It shows normally in every non-dark variant of the GNOME Shell theme.

**Steps to reproduce**

Choose either the Pop-dark or Pop-dark-slim GNOME Shell theme.

**Expected behavior**

The close button should be displayed just like on every other variant of the theme.

**Dark variant** of the GNOME Shell theme **not showing** the **close button**:
![pop_dark](https://user-images.githubusercontent.com/5316157/34310301-a68b7778-e74e-11e7-9470-3ea76fe49378.png)

**Non-dark** variant of the GNOME Shell theme **showing** the **close button**:
![pop](https://user-images.githubusercontent.com/5316157/34310314-c6acdb28-e74e-11e7-82ab-81ca9e97c909.png)

**Comment by isantop** [comment]
Yep, looks like dark assets are installing into a folder called `assets-dark` instead of `assets`
