### ISSUE TITLE
Provide `.terminal` styles

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#113]
~I can get you a GTK style class~

The `.terminal` class is used by apps like the Installer and AppCenter for terminal-styled log output. It should be styled with a dark background and light foreground, like the Terminal app itself.

**Comment by isantop** [comment]
Is this something that should be in the theme, or the installer's application.css?

**Comment by isantop** [comment]
Fixed in the installer codebase

**Comment by cassidyjames** [comment]
fwiw `.terminal` is also used in other places in elementary OS and elementary apps (like the error dialogs in AppCenter), so it might still make sense to move this to the stylesheet.
