### ISSUE TITLE
Maintainership of Flatpak packages

### ISSUE THREAD

**Issue by TingPing** [pop-os/gtk-theme#116]
There are packages of this theme for Flatpak for PopOS integration that are simply re-packages of the `.deb` file used for releases. They are relatively low maintenance outside of version bumps on release but this is a bit tedious for me as I don't use the theme so I was wondering if anybody involved in the project would be interested in helping out.

https://github.com/flathub/org.gtk.Gtk3theme.Pop  
https://github.com/flathub/org.gtk.Gtk3theme.Pop-light

**Comment by isantop** [comment]
Sure, I think that's probably a great idea. If it's pretty low-maintenence we can take over that for you.

**Comment by TingPing** [comment]
Great, I've granted you write access to the repos. I'll need to create 2 more repos for the `-compact` variants also...

**Comment by isantop** [comment]
I'm going to go ahead and close this then. Thanks for getting that all set up! :+1:

**Comment by loxK** [comment]
Are compact variants coming soon ?

-- 
A laptop owner.

**Comment by Luke-Nukem** [comment]
What is the status on the Compact + Dark variants?
