### ISSUE TITLE
No foreground protection on lock screen

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#118]
I'd have to double-check, but I'm pretty sure the default GNOME stylesheet has more shadow under the clock text on the lock screen. As-is, any wallpaper with a sufficiently light colored center makes the clock illegible. 

![img_20180131_113015](https://user-images.githubusercontent.com/611168/35646480-91cd561e-068c-11e8-9601-f4a89de1420c.jpg)

**Comment by cassidyjames** [comment]
So apparently stock GNOME has a little bit of a shadow here, but not much. If we have control over the CSS, though, we should be able to do much better.

**Comment by isantop** [comment]
Fixed when the GNOME-shell theme was split into its own repo
