### ISSUE TITLE
Font too light in Google Chrome

### ISSUE THREAD

**Issue by adred** [pop-os/gtk-theme#120]
**Reporter info**

```
 * Pop!_OS 17.10 (Artful Aardvark)
 *libgtk-3-0:
  Installed: 3.22.25-0ubuntu0.1
  Candidate: 3.22.25-0ubuntu0.1
  Version table:
     3.22.25-0ubuntu0.1 500
        500 http://us.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.22.24-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages
 * Gnome Shell
 * Pop!_GTK+ Version 3.0.2
 ```

**Related Application and/or Shell theming (or name of widget)**
Google Chrome

**Actual issue**
Font too light in the tabs, URL bar, etc. It's too hard to read.

**Steps to reproduce**
Just install Google Chrome and runt it.

**Expected behavior**
It should be darker. 

**Behavior in Adwaita**
It looks okay in Adwaita.

**Comment by isantop** [comment]
Can you provide a screenshot showing this issue in both Adwaita and Pop_GTK? Chrome appears fine to my eye in the latest version.

**Comment by isantop** [comment]
Closed from lack of response.
