### ISSUE TITLE
Pop-dark-slim theme makes ClamTK text unreadable when running a scan.

### ISSUE THREAD

**Issue by Shickmo** [pop-os/gtk-theme#121]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Pop!_OS 17.10 (Artful Aardvark)
Release:        17.10
Codename:       artful

 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
libgtk-3-0:
  Installed: 3.22.25-0ubuntu0.1
  Candidate: 3.22.25-0ubuntu0.1
  Version table:
 *** 3.22.25-0ubuntu0.1 500
        500 http://us.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.22.24-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages

 * Desktop environment - 
 * Pop version - (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```)
 ```
/***************************
 * Pop!_GTK+ Version 3.0.2 *
 ***************************/

**Related Application and/or Shell theming (or name of widget)**

ClamTK

**Actual issue**
When running the Pop-dark-slim theme portions of the UI of ClamTK are unreadable. For example if you try to schedule a scan you can't even see the plus to add the scan. Likewise, when you perform a scan you can't read the showing the number of files scanned nor the number of threats found. If you switch to 
Pop-light-slim for example you can read all of the details in the above examples with no issues.

**Steps to reproduce**
Install ClamTK and set the theme to Pop-dark-slim in Gnome Tweaks. Launch ClamTK and navigate to the scheduler menu. Try to schedule a scan or see a plus icon anywhere in the UI.

**Expected behavior**
I should be able to see the plus icon to schedule a scan and likewise be able to see the text when the scan is running.

**Behavior in Adwaita**
I can see the plus icon in the scheduler menu with no issues and likewise when I run a scan I can read the files scanned and threats text.

**Other Note (feature-request, question, etc...)**
Upon further research from the above it appears that if I disable the Global Dark Theme setting, while having the Pop-dark-slim theme selected, and reopen ClamTK I can see the plus in the scheduler menu but still can't read the text when running a scan for files scanned or threats detected text.

**Comment by isantop** [comment]
Can you upload a screenshot of ClamTK in both Pop-Dark and Adwaita Dark?

**Comment by isantop** [comment]
Closing this for now, since it's been in blocked for over a month.
