### ISSUE TITLE
Firefox check boxes and radio buttons too large

### ISSUE THREAD

**Issue by iGormilhit** [pop-os/gtk-theme#122]
**Reporter info**

```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.28-1
 * Desktop environment - Gnome 3.26.2
 * Pop version - 2.2.3r0
 ```

**Actual issue**

When the Pop! GTK-theme is activated, in Firefox the check boxes and the radio buttons are very large, sometimes disturbing the layout of the page.

![capture1](https://user-images.githubusercontent.com/1557213/36340764-8c2cd482-13e3-11e8-827c-a9ae51163262.png)
![capture2](https://user-images.githubusercontent.com/1557213/36340765-8f759bb0-13e3-11e8-956f-bad3d557c3c3.png)
![531](https://user-images.githubusercontent.com/1557213/36340766-981517e6-13e3-11e8-8e76-186964bd3ee5.png)

**Steps to reproduce**

Install the Pop! Gtk theme from the [AUR repository](https://aur.archlinux.org/packages/pop-gtk-theme/), activated it in the Gnome Tweak Tool, open the firefox profile manager (`firefox -p`) or a page with check boxes (i.e https://ils.test.rero.ch/search?page=1&size=20&q= ) and see that the check boxes are very large.

**Expected behavior**

The check boxes and radio buttons should be less large.

**Behavior in Adwaita**

The check boxes and radio buttons are well sized.

![533](https://user-images.githubusercontent.com/1557213/36340837-ca8e39c2-13e4-11e8-831e-6ae8be162129.png)
![532](https://user-images.githubusercontent.com/1557213/36340839-ce0f2688-13e4-11e8-90f9-0271eb4b3164.png)
![534](https://user-images.githubusercontent.com/1557213/36340840-d0a265e0-13e4-11e8-9f13-d9b5bba692c7.png)

**Comment by drakkan** [comment]
please try the latest pop version

https://aur.archlinux.org/packages/pop-gtk-theme-bin

this issue should be solved

**Comment by iGormilhit** [comment]
@drakkan The lastest version, through the pop-gtk-theme-bin package, solve it, indeed.

Thanks!

**Comment by isantop** [comment]
Glad that got resolved! I wasn't able to replicate this here, so it's good to know it was a simple package issue.

**Comment by v01d** [comment]
Hi, I'm on pop-os and I have the same issue now, visible on firefox. If this was solved back then, what could be happening?

**Comment by v01d** [comment]
I just found a workaround (from here: https://www.reddit.com/r/pop_os/comments/bglcvb/firefox_checkbox_inputs/):

1. Go to about:config in firefox
2. Right click, new -> string. Name: widget.content.gtk-theme-override, Value: Adwaita
3. Restart firefox

**Comment by SimonMellerin** [comment]
Hi, 

Same here on firefox, checkbox are too large and break lot of layout.

Is there any new on this issue ?

**Comment by leviport** [comment]
@SimonMellerin Please provide screenshots and your OS version. I'm not seeing the issue on 21.04.

**Comment by SimonMellerin** [comment]
![image](https://user-images.githubusercontent.com/29925135/116561490-a9478f00-a902-11eb-8153-397da86ad33e.png)

I'm in Ubuntu 20.04.2 LTS

**Comment by v01d** [comment]
BTW, on 20.10 I had to set firefox to use Pop-dark instead of Pop in the override config I mentioned before. Otherwise unchecked checkboxes appear almost invisible.
