### ISSUE TITLE
GDM theme for lock screen not changed

### ISSUE THREAD

**Issue by marioaria** [pop-os/gtk-theme#123]
**Reporter info**

```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.25-0ubuntu0.1
 * Desktop environment - GNOME
 * Pop version - 3.0.2
 ```

**Related Application and/or Shell theming (or name of widget)**
GDM

**Actual issue**
When unlocking screen Ubuntu's default GDM theme is used

**Steps to reproduce**
Lock the screen and then try to unlock it

**Expected behavior**
I expect to see Pop theme

**Behavior in Adwaita**
Adwaita uses default Ubuntu's theme

**Other Note (feature-request, question, etc...)**
Pop theme is correctly used when logging in after reboot or shut down

**Comment by isantop** [comment]
Thanks for your issue! GDM is themed very separately from your desktop, and its theme is the one specified by default for GNOME Shell. It is possible to use the Pop theme on GDM in Ubuntu, but it's very likely to break in updates and not recommended.

**Comment by marioaria** [comment]
When I installed the pop-theme package, it also updated the GDM theme and as I mentioned, it works when I'm logging in (I see the gray background and so on...), but if I'm unlocking, the background is purple (Ubuntu's default).

English isn't my first language, but if I'm reading the answer right, it seems that the bug is then GDM getting updated in the first place? What ever the case, right now it's breaking the consistency.

**Comment by marioaria** [comment]
@isantop Not sure how closed issues work, so I'm mentioning you just to be sure :blush:

**Comment by marioaria** [comment]
Installing and using `pop-session` fixes the issue, but I belive that this shouldn't be the solution.

**Comment by isantop** [comment]
The `ubuntu-session` package configures GDM to use the Ubuntu theme. `pop-session` does the same for the Pop theme. You're right that installing `pop-session` isn't a good solution, but it's the only solution that works in Ubuntu (and it's one of the reasons we recommend using Pop_OS if you want the GDM theme).
