### ISSUE TITLE
Xfce panel text clipped, PulseAudio applet incorrect background/icon

### ISSUE THREAD

**Issue by Pshemas** [pop-os/gtk-theme#124]
* Distribution: openSUSE Leap 42.3
 * Gtk+ 3.0 version: 3.20
 * Desktop environment - Xfce 
 * Pop version - Pop!_GTK+ Version 3.0.2

First of all - love the theme, nice change to finally have a nice looking, modern theme that is not primarily cold in hue.
But I'm having some problems with it on Xfce. First of all , by default the text on the panel buttons (top and bottom portion of the text) is being cut / clipped. You have to make the panel quite big to get rid of this problem. Also applet for minimizing all windows does not use correct icon.

Atm I'm tinkering with it a bit by adding 3rd-party.rc file from Adapta theme to the mix. It fixes most of the problems.
But one remains - pulseaudio applet (not the default volume applet). It has incorrect background color and incorrect icon color (except in Pop-Dark , where only background is incorrect - black), not matching rest of the theme.
Any suggestions how can I tweak the theme to make it work?

**Comment by isantop** [comment]
Can you send in a sccreenshot of the issues you're seeing?

**Comment by isantop** [comment]
Closing for now, since this has been in blocked for over a month.
