### ISSUE TITLE
Generic `.panel` styling

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#13]
A few GTK-based panels including [@elementary/wingpanel](https://github.com/elementary/wingpanel) add a GTK style class of `panel`. We could easily add a `.panel` selector and set the background color to the same value we're using for the GNOME Shell panel.

**Comment by isantop** [comment]
Yep, and we also need to look at the text/label widgets inside of panels. If you can get a list of selectors, I can apply some theming.

**Comment by cassidyjames** [comment]
Here are the relevant bits from the elementary stylesheet: https://github.com/elementary/stylesheet/blob/master/gtk-3.0/apps.css#L276

**Comment by isantop** [comment]
Fixed in `master_cosmic`
