### ISSUE TITLE
HeaderBar w/ SpinButton

### ISSUE THREAD

**Issue by mmstick** [pop-os/gtk-theme#145]
Would we consider this to be an issue?

![screenshot from 2018-04-13 15-13-00](https://user-images.githubusercontent.com/4143535/38753698-3dbc393a-3f2d-11e8-8ba2-5f61de33dc91.png)

How it looks in Adwaita:

![screenshot from 2018-04-13 15-13-25](https://user-images.githubusercontent.com/4143535/38753703-43a6a984-3f2d-11e8-9fa9-e459a0ac3a70.png)

**Comment by jackpot51** [comment]
Probably so

**Comment by isantop** [comment]
Fixed in `master_cosmic`
