### ISSUE TITLE
Style separators in popovers

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#146]
Popovers can have Gtk.Separators, and they're styled in Adwaita and themes like elementary. It looks a bit awkward to not have any visual separation with them in Pop!

For example, we're using one in the installer's partition menu: https://github.com/pop-os/installer/pull/90

In the Pop! screenshots in that PR, I added a simple `separator { background-color: #eee }` to demo it, but they're currently invisible in Pop.

**Comment by cassidyjames** [comment]
This is more than just in popovers. It appears we aren't styling separators anywhere in the theme. I'm happy to not draw them in headerbars, but we really should draw them elsewhere. There are a couple of spots in the installer now that look off due to them being unstyled, and other apps (like Tootle) are much harder to read without them.

**Comment by isantop** [comment]
Fixed in the v4 build

**Comment by isantop** [comment]
Fixed in `master_cosmic`
