### ISSUE TITLE
The check button is always red!!

### ISSUE THREAD

**Issue by LonelySqrt** [pop-os/gtk-theme#147]
![screenshot from 2018-04-16 17-18-27](https://user-images.githubusercontent.com/24912241/38800897-0368e3f8-419b-11e8-9e2e-4b8db0b26e42.png)

**Comment by isantop** [comment]
Something looks not-right here. The window controls are not correct there. What version of the theme do you have installed, what OS  and version are you running, and what is your GTK version?

**Comment by LonelySqrt** [comment]
Pop theme: pop-remix 1.3.
OS: Ubuntu17.10
GTK3: 3.22.25-0ubu
GTK2: 2.24.31-2ubu
Thank you for your concern.

**Comment by isantop** [comment]
What is the pop-remix theme? I don't think that's maintained here.

**Comment by isantop** [comment]
I'm going to go ahead and close this for now. It looks like a bug in a fork of the Pop theme.
