### ISSUE TITLE
CDS Windows - Buttons needs adjustments

### ISSUE THREAD

**Issue by OliverScholtz** [pop-os/gtk-theme#151]
The image says all...

![captura de pantalla de 2018-04-28 00-29-48](https://user-images.githubusercontent.com/38477330/39387732-9521b174-4a7b-11e8-940f-00294b3d17c9.png)

**Comment by OliverScholtz** [comment]
I think all "cds" applications are affected...

![captura de pantalla de 2018-04-28 00-34-36](https://user-images.githubusercontent.com/38477330/39387877-78d6ead8-4a7c-11e8-80b8-eda2109d40b3.png)

![captura de pantalla de 2018-04-28 00-37-21](https://user-images.githubusercontent.com/38477330/39387881-7d7e55da-4a7c-11e8-9ec5-83ac5529074e.png)

**Comment by OliverScholtz** [comment]
It's a bug in Wayland, only, in Xorg Mode everythink is well

**Comment by isantop** [comment]
I don't know that this has cropped up on our Wayland testing here. Perhaps if @cassidyjames could give it a try (I have an Nvidia card and can't test Wayland)

**Comment by isantop** [comment]
Recent wayland testing has not to my knowledge revealed any issues like this (looking at 18.10 and newer), so I'm going to close this for now. Please open a new issue if this issue is still occurring.
