### ISSUE TITLE
Too low contrast between tooltip background and list background in open dialog file

### ISSUE THREAD

**Issue by Corsseir** [pop-os/gtk-theme#155]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 * Desktop environment - 
 * Pop version - (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```)
 ```
corsseir@ltc0:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 18.04 LTS
Release:	18.04
Codename:	bionic

corsseir@ltc0:~$ apt policy libgtk-3-0
libgtk-3-0:
  Installed: 3.22.30-1ubuntu1
  Candidate: 3.22.30-1ubuntu1
  Version table:
 *** 3.22.30-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

Gnome Shell

corsseir@ltc0:~$ head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css
/***************************
 * Pop!_GTK+ Version 3.1.0 *
 ***************************/
**Related Application and/or Shell theming (or name of widget)**
---

**Actual issue**
Too low contrast between tooltip background and list background in open dialog file:
![3](https://user-images.githubusercontent.com/11137173/39445226-a8ead852-4cba-11e8-8f52-84ebb4451183.png)

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**
OK

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
I can't seem to replicate this on my end here. All tooltips have shadows. What application/widgets are you seeing this issue with (That doesn't match the file chooser dialog that comes with GTK3).

**Comment by isantop** [comment]
The GTK3 file-open dialog, for reference:

![screenshot from 2018-05-01 08-26-49](https://user-images.githubusercontent.com/5883565/39479258-8db98cea-4d19-11e8-8218-be2922a1a10d.png)

**Comment by isantop** [comment]
Ah, I'd guess that GTK 2 apps don't get shadows around tooltips.
