### ISSUE TITLE
suggestion #1 Buttons

### ISSUE THREAD

**Issue by OliverScholtz** [pop-os/gtk-theme#158]
For considering, please try if you like ... I like it, for me it's a improvement:

**

button.image-button, actionbar > revealer > box .linked > button.image-button:not(.suggested-action):not(.destructive-action):not(.server-list-button), .titlebar:not(headerbar) .linked > button.image-button:not(.suggested-action):not(.destructive-action),
headerbar .linked > button.image-button:not(.suggested-action):not(.destructive-action), .app-notification .linked > button.image-button, toolbar .linked > button.image-button, headerbar .linked.vertical > button.image-button:not(.suggested-action):not(.destructive-action), .app-notification .linked.vertical > button.image-button, toolbar .linked.vertical > button.image-button, .linked > button.flat.image-button, .linked.vertical > button.flat.image-button, .inline-toolbar button:not(.text-button), button.titlebutton, .raven .raven-header:not(.top) button.image-button, .raven .expander-button, .nautilus-window headerbar > revealer > button {
  border-radius: 4px;
  -gtk-outline-radius: 5px;
}

button.minimize, button.maximize, button.close, button.circular {
  border-radius: 9999px;
  -gtk-outline-radius: 9999px;
}

**

for gtk.css and gtk-dark.css

Thank you for considering and trying

I use Pop-slim Theme and this tweak make it more eye-candy.

**Comment by isantop** [comment]
I'm not seeing any differences when I apply this CSS within the inspector. Can you post a screenshot showing the differences?

**Comment by OliverScholtz** [comment]
![captura de pantalla de 2018-05-07 18-56-27](https://user-images.githubusercontent.com/38477330/39714433-5d757ee8-522a-11e8-9166-99b33d47c5fc.png)

**Comment by OliverScholtz** [comment]
![captura de pantalla de 2018-05-07 18-52-34](https://user-images.githubusercontent.com/38477330/39714453-66b8099e-522a-11e8-988c-c2cbaa1502d6.png)

**Comment by OliverScholtz** [comment]
Put Geary, the Trash Icon is different with the rest buttons (hover) by default. After this change, it fits with the rest.

The only problem is, that the message-box in Nautilus, the hover over the x-buttons isn't round anymore. But this can be corrected with putting the correct source in
`button.minimize, button.maximize, button.close, button.circular {`

**Comment by isantop** [comment]
I don't think I like changing the image buttons to use square outlines instead of circles. It's one of the things that helps distinguish Pop from other themes.

**Comment by OliverScholtz** [comment]
then in Geary, for example, all hovers on buttons have to be round, too. You don't think?

**Comment by isantop** [comment]
That would be ideal. I'm not sure why Geary isn't setting all of those buttons to have the .image-button style class, but they should be. However, that's more of an issue with Geary than with the theme.

**Comment by isantop** [comment]
The v4 build of the theme will use rectangular button shapes for everything except `.rounded` buttons.

**Comment by isantop** [comment]
Fixed in `master_cosmic`
