### ISSUE TITLE
No shell theme on GNOME 3.28

### ISSUE THREAD

**Issue by ErikWallstrom** [pop-os/gtk-theme#159]
**Reporter info**

```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.30-1
 * Desktop environment - GNOME 3.28.1
 * Pop version - 3.1.0
 ```

**Actual issue**

I cannot find any shell theme after installing the theme from source (git). 

**Steps to reproduce**

Install from source.

**Expected behavior**

I expect there to be a shell theme (I have used it before)

**Comment by isantop** [comment]
The Shell theme has been split into a separate repository to simplify maintenance. You can get the Shell theme at pop-os/gnome-shell-theme and build it using `make && sudo make install`
