### ISSUE TITLE
Unable to locate package pop-theme

### ISSUE THREAD

**Issue by bryanwillis7** [pop-os/gtk-theme#162]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 * Desktop environment - 
 * Pop version - (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```)
 ```

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
I'm getting

E: Unable to locate package pop-theme

After trying to install this theme with the three commands listed in your installation guide. I'm on ubuntu 16.04. Any help would be greatly appreciated. Thanks.

**Steps to reproduce**
sudo add-apt-repository ppa:system76/pop
sudo apt update
sudo apt install pop-theme

**Expected behavior**
It should have installed?

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
The Pop theme isn't currently packaged for Ubuntu prior to 17.10. You'll need to upgrade or you can build the theme from the source code on github:

https://github.com/pop-os/gtk-theme
http://github.com/pop-os/gnome-shell-theme
