### ISSUE TITLE
GNOME Calendar button is cut off in this theme.

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/gtk-theme#164]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

libgtk-3-0:
  Installed: 3.22.30-1ubuntu1
  Candidate: 3.22.30-1ubuntu1
  Version table:
 *** 3.22.30-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

GNOME Shell

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**

/***************************
 * Pop!_GTK+ Version 3.1.0 *
 ***************************/

**Related Application and/or Shell theming (or name of widget)**

GNOME Calendar and Pop GTK Theme

**Actual issue**

![screenshot from 2018-05-16 15-27-03](https://user-images.githubusercontent.com/4884946/40145130-f3fc39fc-591d-11e8-8fbf-b23a93d19f47.png)

**Steps to reproduce**

1. Open GNOME Calendar
2. Click to add a new event
3. See left and right bottom buttons

**Expected behavior**

Buttons are even

**Behavior in Adwaita**

![screenshot from 2018-05-16 15-26-51](https://user-images.githubusercontent.com/4884946/40145163-1265ada6-591e-11e8-86f7-aa8332516c5a.png)

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
The buttons noted are changed to flat-style buttons in the v4 of the theme.

**Comment by isantop** [comment]
Fixed in `master_cosmic`
