### ISSUE TITLE
Libre Office Gtk2 Theme is ugly

### ISSUE THREAD

**Issue by OliverScholtz** [pop-os/gtk-theme#165]
Pop Os 18.04 - 18.05.2018 - all updated

![captura de pantalla de 2018-05-18 00-05-19](https://user-images.githubusercontent.com/38477330/40206571-e97d641a-5a30-11e8-9b4e-df359ce05a4d.png)

Open "Print" - Window for the see the screenshot.

Options, Personalization etc. is the same.

Buttons are without style and a grey point in the ends above.

**Comment by isantop** [comment]
Libreoffice draws its own theme based on the GTK theme present. Naturally, some misinterpretation of the theme is expected, and unfortunately, I think that's what's happening here. Nothing here looks too out of place apart from the expander arrow, so I'll have a look at that and see what changes.

**Comment by isantop** [comment]
Many of these issues are caused by bugs with the LibreOffice GTK3 engine. Hopefully this improves in the future. Many of these issues (antialiased check/radio items, etc) are also present in Adwaita, so there's not really much we can do in Pop apart from waiting on LO.
