### ISSUE TITLE
Pop themes aren't displayed in the GtkInspector's drop down menu

### ISSUE THREAD

**Issue by nana-4** [pop-os/gtk-theme#168]
**Distribution:** Tested on Fedora 28 & Ubuntu 18.04

**Gtk+ 3.0 version:** 3.22.30

**Desktop environment:** GNOME Shell 3.28.2

**Pop version:** 3.1.1

**Related Application and/or Shell theming (or name of widget)**

All GTK3 apps

**Actual issue**

Pop themes aren't displayed in the GtkInspector's drop down menu.

![image](https://user-images.githubusercontent.com/9556384/40524957-6a6d235c-6018-11e8-8a51-8253c2227c79.png)

**Steps to reproduce**

1. Run: `GTK_DEBUG=interactive gtk3-widget-factory`
2. Go to "Visual" tab.
3. Click the combo button of "GTK+ Theme".

**Expected behavior**

Pop themes should be displayed in the GtkInspector's drop down menu.

**Behavior in Adwaita**

Adwaita is properly displayed in the drop down menu.

**Other Note (feature-request, question, etc...)**

It seems it's because there is no `gtk-3.0/` in `/usr/share/themes/Pop*/`. I think `gtk-3.20/` needs to be installed as `gtk-3.0/`.

For quick testing:

```sh
sudo mv /usr/share/themes/Pop/gtk-{3.20,3.0}
```

**Comment by isantop** [comment]
I have been looking for the solution to this for the longest time. That fix does indeed appear to fix it.

One note; the 3.2x folder should probably be _copied_ to the 3.0 folder to ensure that the theme remains fully versioned. A symlink would work well for this purpose.
