### ISSUE TITLE
Compact theme headerbar too large with switch widget

### ISSUE THREAD

**Issue by mcclurgm** [pop-os/gtk-theme#174]
**Distribution (run `cat /etc/os-release`):**
Fedora 28 (Workstation Edition)

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.22.30

**Desktop environment:**
GNOME Shell 3.28.2

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
2.2.3r0

**Related Application and/or Shell theming (or name of widget)**
GNOME Tweaks (Tweak Tool), GNOME Settings.

Affected widgets: GtkHeaderBar and GtkSwitch (might affect other widgets in HeaderBar, but I haven't found other instances)

**Actual issue**
When the headerbar contains a switch control, it has a taller height than other headerbars. It's larger than empty or with simple buttons (like Nautilus).

This does not happen in other themes: Adwaita, Adapta, etc. Similarly, non-"compact" Pop themes don't have this behavior. Other widgets, like a typical button or the breadcrumbs in Nautilus, don't have this affect. The larger height seems to be unique to the switch widget. 

![tweaks-empty-header](https://user-images.githubusercontent.com/29022469/42253930-5a73c462-7f01-11e8-8011-abe06057ae3b.png)
![tweaks-switch-header](https://user-images.githubusercontent.com/29022469/42253931-5a9071e8-7f01-11e8-9443-317a62c79ce9.png)

**Steps to reproduce**
With Pop-compact, Pop-dark-compact, or Pop-light-compact theme enabled, switch between Extensions and any other pane in GNOME Tweaks. The height difference will move main window content down. The same effect happens in the WiFi pane in GNOME Settings.

Similarly, open up one of these panes and put the window next to Nautilus or any other default GNOME app. The headerbar with the switch will be taller.

**Expected behavior**
HeaderBar height remains the same as without a switch.

**Behavior in Adwaita**
Same as expected: the dimensions of the headerbar widget remain the same in both pages in my Settings example.

**Other Note (feature-request, question, etc...)**
If I had to guess, the switch is too tall for the default HeaderBar height to accommodate. I don't know much about Gtk though, so I don't know how to look into this.

**Comment by isantop** [comment]
This is an issue that's fixed in version 3 of the Pop theme. You can get it from git directly, or wait for the packager in Fedora to update the package.
