### ISSUE TITLE
System Monitor: resource tab usage progress bar regression

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#178]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.04

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.22.30

**Desktop environment:**
GNOME

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
Installed from `pop-gtk-theme_3.99.1.1533659735.18.04.92c7ad1_all.deb` 
Running regular `Pop-4` theme

**Actual issue**
In the System Monitor tool, under the resource tab, the progress bar for the file system percentage used is not as easily understandable as the progress bar itself seems to be white (which is the color of the background)

Sorry but I feel like the best way to show the oddity is with screenshots, enjoy!

__In the Beta__
![screenshot from 2018-08-07 21-22-37](https://user-images.githubusercontent.com/7460774/43804601-d01d7370-9a59-11e8-8534-97b7650c2f30.png)

![selected](https://user-images.githubusercontent.com/7460774/43804606-d17c4124-9a59-11e8-97ce-60e11347a2de.png)

__Previous version__

![screenshot from 2018-08-07 15-53-05](https://user-images.githubusercontent.com/7460774/43804896-e9433cd0-9a5a-11e8-8bc2-7b36f02ecfd2.png)

![screenshot from 2018-08-07 15-53-14](https://user-images.githubusercontent.com/7460774/43804897-eb261dec-9a5a-11e8-8f69-8ebc427a0c2c.png)

**Comment by isantop** [comment]
Fixed in `master_cosmic`
