### ISSUE TITLE
Path bar oddity with `Desktop`

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#179]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.04

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.22.30

**Desktop environment:**
GNOME

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
Installed from `pop-gtk-theme_3.99.1.1533659735.18.04.92c7ad1_all.deb` 
Running regular `Pop-4` theme

**Actual issue**
In Baobab (disk usage analyzing application), when selecting `Scan Folder`, a file menu appears. The forward slash(`/`) is present on the path bar when selecting all of the default folders (Documents, Downloads, Pictures, Music, Videos) except for `Desktop`. `Desktop` on the other hand has the Desktop logo but no `/`.

__What I see under ``Music``(expected)__
![music](https://user-images.githubusercontent.com/7460774/43805286-71ae1210-9a5c-11e8-91be-0efc945b096d.png)

__What I see under ``Desktop``(not expected)__
![desktopslash](https://user-images.githubusercontent.com/7460774/43805097-beb6f19a-9a5b-11e8-86d5-e8de2c1dea49.png)

**Comment by brs17** [comment]
I can confirm this happens in any `Select Folder` popup

**Comment by isantop** [comment]
There should probably be a separator after the home-folder as well.

**Comment by isantop** [comment]
Fixed in `master_cosmic`
