### ISSUE TITLE
Seahorse ux becomes less readable

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#182]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.04

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.22.30

**Desktop environment:**
GNOME

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
Installed from `pop-gtk-theme_3.99.1.1533659735.18.04.92c7ad1_all.deb` 
Running regular `Pop-4` theme

**Actual issue**
Seahorse categories became unreadable with new theme

__Before__
![origsea](https://user-images.githubusercontent.com/7460774/43849761-6e222a54-9af3-11e8-9f68-a5356b19c7ec.png)

__After__

![seahorse](https://user-images.githubusercontent.com/7460774/43849765-6fac1416-9af3-11e8-8569-bf11e4e467f6.png)

**Comment by isantop** [comment]
Fixed in `master_cosmic`
