### ISSUE TITLE
EOG zoom percentage is cutoff

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#183]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.04

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.22.30

**Desktop environment:**
GNOME

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
Installed from `pop-gtk-theme_3.99.1.1533659735.18.04.92c7ad1_all.deb` 
Running regular `Pop-4` theme

**Actual issue**
Eye of Gnome zoom percentage is cutoff (when >3 characters). This is not the case in the previous version of the gtk-theme.

![eog](https://user-images.githubusercontent.com/7460774/43849835-954e62be-9af3-11e8-8952-438781599ea4.png)

**Comment by isantop** [comment]
Fixed in `master_cosmic`
