### ISSUE TITLE
Password verification message in installer is difficult to read

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#184]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.04

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.22.30

**Desktop environment:**
GNOME

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
Installed from `pop-gtk-theme_3.99.1.1533659735.18.04.92c7ad1_all.deb` 
Running regular `Pop-4` theme

**Actual issue**
In the installer, the message that appears regarding a poor password choice is a very light color that I think is too similar to the background color to read clearly.

![lowcontrast](https://user-images.githubusercontent.com/7460774/43850824-409e49e8-9af6-11e8-9ec0-7d6c4cdee2f5.png)

**Comment by brs17** [comment]
After having seen this screen quite a lot in preparation for 18.10 release last week, I think this message is still too low contrast. I notice in the old version of the theme, these messages were just in black (and therefore very easy to read), perhaps we revert back to that?

**Comment by isantop** [comment]
The message text is being set the style class on the text. Reverting to black would require breaking this feature or changing Pop_Shop
