### ISSUE TITLE
Labels don't dim in backdrop state

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#187]
Running up-to-date v4 branch (6c78e5958576bef17f3c79e700ffc22058b78be5). It looks like most widgets dim when the window is in the backdrop state, but labels stay full-brightness.

|  | Focused | Backdrop |
|--|------------|--------------|
| Light | ![screenshot from 2018-08-08 12 16 26](https://user-images.githubusercontent.com/611168/43856203-1ffcf432-9b05-11e8-89d8-792dee919941.png) | ![screenshot from 2018-08-08 12 16 38](https://user-images.githubusercontent.com/611168/43856340-75daa476-9b05-11e8-925c-6d6abc29ce52.png) |
| Dark | ![screenshot from 2018-08-08 12 15 49](https://user-images.githubusercontent.com/611168/43856233-351dbf40-9b05-11e8-8aaf-93f53d1092e7.png) | ![screenshot from 2018-08-08 12 16 01](https://user-images.githubusercontent.com/611168/43856241-3a8ee5da-9b05-11e8-9814-2a9a25212d9e.png) |

**Comment by isantop** [comment]
I have a demo of this, but it becomes a bit hard to tell that the widgets in the window aren't diabled when the window is in the background.

**Comment by isantop** [comment]
Making labels dim in the backdrop state can make backdrop windows harder to read while additionally making many widgets look disabled. Interactive widgets should dim in the backdrop, but standard informational ones should now.
