### ISSUE TITLE
Flatpak variants

### ISSUE THREAD

**Issue by loxK** [pop-os/gtk-theme#197]
Could we please have the over variants of the theme packages for flatpak please? I am an active user of the compact version. Only those two are available as of now:

https://github.com/flathub/org.gtk.Gtk3theme.Pop
https://github.com/flathub/org.gtk.Gtk3theme.Pop-light

**Comment by isantop** [comment]
Flatpak variants will be updated when the new V4 is released.

**Comment by isantop** [comment]
@loxK After looking at this, it looks like flathub will need to have new repos created for the missing variants. This isn't something I can do over there since I don't own or manage that organization. All I can do is update the packages that are provided.

**Comment by loxK** [comment]
I think v4 is out.

There should be[ a way to ask for new repos](https://github.com/flathub/flathub/wiki/App-Submission) I guess

**Comment by nedrichards** [comment]
Hi there, does that mean that upstream would like to be involved with these PRs:

https://github.com/flathub/flathub/pull/923/
https://github.com/flathub/flathub/pull/924
https://github.com/flathub/flathub/pull/925

If so, we'll accept them sharpish and can add credentials for whoever is needed.

**Comment by isantop** [comment]
Flatpak themes are currently up to date with 5.0.
