### ISSUE TITLE
Feature Request: Alternate Color Schemes

### ISSUE THREAD

**Issue by jlacroix82** [pop-os/gtk-theme#199]
I thought I would submit a simple feature request: alternate color schemes for the Pop!_OS theme. The theme is amazing but alternate colors would allow for more customization. By alternate colors, I'm moreso referring to highlights, etc. I think it would be great to have alternate colors available, such as gray, green, blue, and so on. This would give users greater customization without having to resort to themes from gnome-look.org which are of varying quality.

**Comment by isantop** [comment]
While this would be a neat addition, we already have 6 variants of the theme (Standard and Slim versions each of Normal, Dark, and Light-titlebar colors). That said, the theme is pretty easy to customize if you want to change the colors. Edit the color values in the `recolor-assets.sh` script in the `src/gtk2` folder, then change the values for the Color-1 (Blue by default) and Color-2 (Orange) variables.

**Comment by isantop** [comment]
Closing for now, as this wishlist feature isn't currently feasible given current GNOME architectures.

**Comment by maximegel** [comment]
@isantop's answer seems to be outdated. That would be great if you could describe how to change the theme name and colors for the latest version.

**Comment by crummyh** [comment]
At some point this script was removed. If you want to see it, [this](https://github.com/pop-os/gtk-theme/blob/37a6b468ef254a42f1faef802c2af44508bced95/src/gtk2/recolor-assets.sh) was what it looked like on the day of @isantop's answer. Someone might be able to re-add that script (if it still works), or you can use [pocse](https://github.com/guisalmon/pocse).

**Comment by crummyh** [comment]
The file [_pop_os-palette.scss](https://github.com/pop-os/gtk-theme/blob/master/gtk/src/light/gtk-4.0/_pop_os-palette.scss) seems to be similar. (Note: Only in the light theme folder) Changing the values and building from source might do the trick. I haven't tried though. This will likely only work with GTK-4 & GTK-3.
