### ISSUE TITLE
Did not find color property

### ISSUE THREAD

**Issue by sentient** [pop-os/gtk-theme#209]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

libgtk-3-0:
  Installed: 3.22.30-1ubuntu1
  Candidate: 3.22.30-1ubuntu1
  Version table:
 *** 3.22.30-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
/***************************
 * Pop!_GTK+ Version 3.1.2 *
 ***************************/

**Related Application and/or Shell theming (or name of widget)**

Stating the gnome-terminal

**Actual issue**

Syslog will display many messages 

Sep  7 09:31:43 pop-os systemd[4163]: Started GNOME Terminal Server.
Sep  7 09:31:43 pop-os gnome-shell[4310]: Did not find color property '-arrow-background-color'
Sep  7 09:31:43 pop-os gnome-shell[4310]: Did not find color property '-arrow-background-color'
Sep  7 09:31:54 pop-os gnome-shell[4310]: Ignoring excess values in shadow definition
Sep  7 09:31:54 pop-os gnome-shell[4310]: Ignoring excess values in shadow definition

**Steps to reproduce**

Launch gnome terminal

**Expected behavior**

No syslog messages

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

Used official pop-os theme

Also tried the latest from github

**Comment by isantop** [comment]
Please note that the error messages you're seeing here are from the gnome-shell theme, not the GTK theme. Can you post the version of the pop-gnome-shell-theme package you have installed? 

`apt policy pop-gnome-shell-theme`

**Comment by isantop** [comment]
I can't seem to reproduce this issue here on my machine. Is there anything else that may have been causing this problem for you?
