### ISSUE TITLE
Selected tab in gnome-terminal has orange highlight, even when mouse is not hovering over it

### ISSUE THREAD

**Issue by jackpot51** [pop-os/gtk-theme#213]
![screenshot from 2018-10-05 11-27-41](https://user-images.githubusercontent.com/7741236/46550288-dd18c000-c891-11e8-9479-a680445d5ab3.png)

**Comment by isantop** [comment]
This is a deliberate design decision intended to further emphasize the current tab. Other tabs in the theme should be sharing this styling.
