### ISSUE TITLE
gnome-terminal: focused/unfocused transition

### ISSUE THREAD

**Issue by drakkan** [pop-os/gtk-theme#217]
**Distribution:**

Arch Linux

**Gtk+ 3.0 version:**

3.24.1+8+g220f77d8c1

**Desktop environment:**

Gnome shell 3.30.1

**Pop version:**

4.0.0

https://aur.archlinux.org/packages/pop-gtk-theme-bin

**Related Application and/or Shell theming (or name of widget)**

gnome-terminal

**Actual issue**

please take a look at the screencast here:

http://94.177.162.225/temp/Screencast_gnome_terminal_popv4.webm

**Comment by brs17** [comment]
I can confirm similar behavior happens on the latest build for Pop!_OS 18.10

**Comment by drakkan** [comment]
using 047192b the issue is greatly improved but not completly fixed, thanks!
