### ISSUE TITLE
Do not disturb toggle does not match rest of theme

### ISSUE THREAD

**Issue by kylecorry31** [pop-os/gtk-theme#226]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2
  Version table:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**
GNOME 3.30.1

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0
Copyright 2017-2018 System76, Inc.

**Related Application and/or Shell theming (or name of widget)**
GNOME Shell Switch (Do Not Disturb extension)

**Actual issue**
The toggle for Do Not Disturb does not match the style of the other toggles - this style is set in the Shell theme for Pop. 

**Steps to reproduce**
Open the notification panel and look at the DND switch.

**Expected behavior**
The switch in DND matches the rest of Pop.

**Behavior in Adwaita**
Unknown

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
FYI: Issues about the GNOME Shell theme should be opened against https://github.com/pop-os/gnome-shell-theme

**Comment by kylecorry31** [comment]
Should I move this there?

**Comment by isantop** [comment]
No need for now.
