### ISSUE TITLE
Headerbar buttons are not consistently-sized

### ISSUE THREAD

**Issue by aral** [pop-os/gtk-theme#227]
![pop-18 10-button-sizes-bug](https://user-images.githubusercontent.com/41798/47271708-bdf97e00-d573-11e8-8c3f-924a90878a4f.png)

**Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2
  Version table:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**

 * Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0

**Related Application and/or Shell theming (or name of widget)**

Gnome Shell.

**Actual issue**

The buttons in the theme now have a faint outline. And:

  * Are of inconsistent sizes/heights
  * Have incorrect highlight areas (e.g., hover over the back/forward buttons in Gnome Web. The highlighted area is smaller than the button area and actually looks like the correct size the buttons should be.)

**Steps to reproduce**

Updade from Pop!_OS 18.04 to 18.10 using the instructions at https://blog.system76.com/post/179217201328/see-what-changes-have-been-orbiting-popos (my upgrade had multiple errors and I finally managed to recover from them to install the system but I’m not sure if these are due to that or true for everyone).

**Expected behavior**

* The buttons should not have backgrounds (as per the previous version of the theme in 18.04) and, if they do, they should be of consistent dimensions.

**Behavior in Adwaita**

* The buttons are the correct size.

![web-with-adwaita](https://user-images.githubusercontent.com/41798/47271861-10876a00-d575-11e8-94b6-6bfdd924b2d7.png)

**Comment by isantop** [comment]
Having background behind headerbar buttons is a deliberate design choice compared to Version 3. However, I agree that they should be the same size across the bar. That *should* be easy to fix.

**Comment by aral** [comment]
Ah, that’s unfortunate. 

Aral

**Comment by isantop** [comment]
It's actually a big usability improvement and brings the theme more in line with other themes, which often draw some kind of border or background around buttons. Defining the area that is clickable versus not is a benefit when figuring out where to click on a certain button.

It takes a bit of getting used to compared to the previous version, but once you do it helps greatly.
