### ISSUE TITLE
Dark Theme affecting Firefox on Google Drive/Docs

### ISSUE THREAD

**Issue by alosarjos** [pop-os/gtk-theme#228]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

libgtk-3-0:
  Instalados: 3.24.1-1ubuntu2
  Candidato:  3.24.1-1ubuntu2
  Tabla de versión:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:** Gnome-Shell

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**

 * Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0
 * Copyright 2017-2018 System76, Inc.

**Related Application and/or Shell theming (or name of widget)**: Firefox and Google Docs

**Actual issue**

Using Pop Dark theme, documents title will appear with a black background

**Steps to reproduce**

Create a document on Google Drive within Firefox and check the title (Using the Dark variant)

**Other Note (feature-request, question, etc...)**

It looks fine with normal/light variant

![imagen](https://user-images.githubusercontent.com/29999427/47293657-04e68280-d60b-11e8-9e31-c1e4a774a99d.png)

**Comment by alosarjos** [comment]
Can close, it's an upstream bug, also happening with Adawita Dark...

**Comment by isantop** [comment]
As a workaround for users affected by this issue, you can override the widget theme that Firefox uses for widgets on webpages by going to `about:config`, right clicking and choosing New > String, set the title of the new string to `widget.content.gtk-theme-override`, and then set the value to `Pop`. Closing and reopening the browser should cause this to take effect.
