### ISSUE TITLE
Text colour of links white on white

### ISSUE THREAD

**Issue by nicojx** [pop-os/gtk-theme#240]
**Distribution:** Ubuntu 18.10 (Cosmic Cuttlefish)

**Gtk+ 3.0 version:** - 3.24.1-1ubuntu2

**Desktop environment:** GNOME Shell 3.30.1

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):** Version 4.0.0

**Related Application and/or Shell theming (or name of widget)** Evolution

**Actual issue**
In Evolution, links in emails are displayed white on white. This issue does not appear in other themes.

**Steps to reproduce**
Open HTML email with links in Evolution.

**Expected behavior**
Links show in a colour other than white (i.e. are visible).

**Behavior in Adwaita**
Links show in blue.

**Other Note (feature-request, question, etc...)**

![screenshot from 2018-11-10 22-27-55](https://user-images.githubusercontent.com/1081603/48306810-1353fa00-e538-11e8-8fbc-ea7954a7f792.png)

**Comment by bigbrovar** [comment]
I can confirm this issue. It is pretty much the only issue I have with the popOS theme. Is there anything I can do so that this bug can at least be confirmed?
