### ISSUE TITLE
Too much spacing in menus even on `slim`

### ISSUE THREAD

**Issue by v-marinkov** [pop-os/gtk-theme#243]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2
  Version table:
 *** 3.24.1-1ubuntu2 500
        500 http://ubuntu.mirror.garr.it/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

Gnome 3.30

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**

/*
 * Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0
 * Copyright 2017-2018 System76, Inc.

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

Spacing in menus is way too big even in the `slim` theme. See here https://imgur.com/gallery/1GNK2pl

**Steps to reproduce**

I upgraded from 18.04 to 18.10 and began noticing how big the spacing of menus is in Nautilus and other GTK applications.

**Expected behavior**

This is wasted space and induces more mouse movement. I expect menus to be tighter.

**Behavior in Adwaita**

See here again https://imgur.com/gallery/1GNK2pl

**Other Note (feature-request, question, etc...)**

**Comment by v-marinkov** [comment]
Hi, I just checked again and I see no difference in Libreoffice before and after the update. The screenshots I attached initially still look the same and menus take too much space.

**Comment by isantop** [comment]
What is the output you get from running this command:
```
apt policy pop-gtk-theme
```

**Comment by isantop** [comment]
Looking at the menus on my machine, it looks like LO is deliberately adding a lot of extra padding to check buttons (about double) compared to what GTK is doing. Unfortunately, it seems this might not be solveable without changing the way check boxes look in the rest of the theme.

**Comment by v-marinkov** [comment]
After updating Libre office and 
`pop-gnome-shell-theme:all 4.0.10~1547658215~18.10~7b4db5a 4.0.12~1549054892~18.10~e40c0fc`
everything is fixed now! I don't know which one did it, but I am happy pop-os looks properly now :) Thanks for all the work!
