### ISSUE TITLE
Shadows are left behind in LibreOffice Writer's toolbar after mouse-over

### ISSUE THREAD

**Issue by AGitBoy** [pop-os/gtk-theme#245]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`): Fedora 29 Workstation**

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```): 3.24.1**

**Desktop environment: GNOME**

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```): 4.0.0**

**Related Application and/or Shell theming (or name of widget): LibreOffice**

**Actual issue**
When using theme, on opening libreoffice the buttons in the toolbar look like this:
![start_libreoffice](https://user-images.githubusercontent.com/30708886/48961967-6621ae80-ef47-11e8-8a45-c2e709ec042e.png)
However, when moused over, the buttons in the toolbar sometimes gain a shadow, which, after the mouse leaves, may be left behind, resulting in something looking like this:
![end_libreoffice](https://user-images.githubusercontent.com/30708886/48961992-a54fff80-ef47-11e8-8fa2-1060431bc6b7.png)

**Steps to reproduce**
1. Select the Pop Gtk theme (I have tested this with pop-slim and pop, cannot confirm whether this happens on the light and dark variants)
2. Open libreoffice
3. Mouse over several buttons multiple times

**Expected behavior**
No unexpected new shadows left behind after mousing over the buttons  

**Behavior in Adwaita**
When mouse leaves the buttons, no shadow is left behind.

**Other Note (feature-request, question, etc...)**
On a side note, LibreOffice's colouration seems visually inconsistent to me with this theme.

**Comment by AGitBoy** [comment]
Adapta implements a hack here, but I don't know how useful it is to us in particular:
https://github.com/adapta-project/adapta-gtk-theme/blob/3559df9538505eaa91a22ecf4b08dc22928e9212/gtk/sass/3.20/_3rd-party.scss#L3358-L3388

**Comment by isantop** [comment]
@AGitBoy I believe that doesn't actually touch toolbars or buttons, only tabs. I could be wrong though. 

I believe Adapta uses the Firefox theming in LO through some selector magic, but I'm not 100% certain there. I'll play around with it.

**Comment by AGitBoy** [comment]
Any solution to this will be a hack until LO fixes their bug, unfortunately, and the original maintainer of the Adapta project left, so we can't really ask them about anything. I looked and [this commit](https://github.com/adapta-project/adapta-gtk-theme/commit/f84c23adb01418bda1f5b5cd67c4b1fc3b639f10#diff-54b49a70daa08a2cb7f44509527bf2f5R487)  seems to have something to do with it, but the more I look, it seems as though it was a constant battle to maintain LibreOffice support in adapta.

**Comment by isantop** [comment]
So it appears the way Adapta was doing it was setting the "Fallback" style for the buttons and entries, then setting the native styles (with shadows) on top of that for any child widget of a window with a `.background` class, which seems to be most every native GTK3 app. Seems to work fairly well, but it will need some testing in order to verify that it's the best way to do it.

**Comment by AGitBoy** [comment]
I can confirm that the commit added to the 4.1.0 branch fixes the problem on my machine
![lo](https://user-images.githubusercontent.com/30708886/50549293-393c7780-0c28-11e9-88a0-9a270125e0a1.png)
