### ISSUE TITLE
[Feature request] Use FiraGO in place of Fira

### ISSUE THREAD

**Issue by mstfacmly** [pop-os/gtk-theme#249]
Fira is a great font, and I love its overall design. However, its development has ceased a long time ago. It's thankfully been taken up with the newer [FiraGO project](https://github.com/bBoxType/FiraGO/), which added to Fira's intended use cases, including support for many new languages.

**Comment by beatsbury** [comment]
FiraGO is an interesting project. However, they are yet to add any denseness features (compressed, condensed etc)

**Comment by isantop** [comment]
I'm going to go ahead and close this issue for now. It can be reopened in the future if we see more development with FiraGO
