### ISSUE TITLE
Large dark brown boarder in non-GNOME envrionments

### ISSUE THREAD

**Issue by turing-tech** [pop-os/gtk-theme#250]
**Distribution (run `cat /etc/os-release`):** Manjaro linux

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):** 3.24.1

**Desktop environment:** KDE

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):** 4.0.0

**Related Application and/or Shell theming (or name of widget):** Shell theme is Arc Color

**Actual issue:**
Boarders appear, like the one pictured.

![screenshot](https://user-images.githubusercontent.com/1839673/49492935-28b30000-f828-11e8-9ab0-379ca635c029.png)

**Steps to reproduce:** Open any GTK app (nautilus, gnome calculator, gedit) in KDE with the theme enabled as the GTK theme.

**Expected behavior:** A small, 1-3 pixel boarder appears

**Behavior in Adwaita:** No border

**Comment by isantop** [comment]
I believe this is being caused by other desktops not respecting the GTK Window margin (which we use for resize areas. It might also be caused by the large shadows in the Pop theme.
