### ISSUE TITLE
Extra drag space on Firefox

### ISSUE THREAD

**Issue by alosarjos** [pop-os/gtk-theme#252]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
libgtk-3-0:
  Instalados: 3.24.1-1ubuntu2
  Candidato:  3.24.1-1ubuntu2
  Tabla de versión:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:** Gnome

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
/*
 * Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0
 * Copyright 2017-2018 System76, Inc.

**Related Application and/or Shell theming (or name of widget)** Pop! GTK Theme and Firefox

**Actual issue**
Extra drag space when removing the menu bar

**Steps to reproduce**
Disable the menu bar on Firefox and use the Pop! GTK Theme

**Expected behavior**
Tabs should be at the top limit

**Behavior in Adwaita**
No extra drag space

**Other Note (feature-request, question, etc...)**

Pop! GTK Theme
![captura de pantalla de 2018-12-13 20-18-55](https://user-images.githubusercontent.com/29999427/49962539-c63bbd00-ff15-11e8-8a86-c9a9e842c7fc.png)

Adawita
![captura de pantalla de 2018-12-13 20-30-09](https://user-images.githubusercontent.com/29999427/49962591-e8cdd600-ff15-11e8-90b2-91b8442936ee.png)

**Comment by isantop** [comment]
I'm not 100% sure what is causing this extra space, but I think it's caused by the padding on headerbar elements. That said, it's such a small amount of total extra space that it doesn't significantly hamper usability and in fact enhances it by giving the user more space to grab the window from, which can be an issue when the entire bar is taken up by tabs.

**Comment by alosarjos** [comment]
In those cases on the personalization page of Firefox it's an option for adding extra drag space.
