### ISSUE TITLE
Firefox shows a transparent gap

### ISSUE THREAD

**Issue by arturolinares** [pop-os/gtk-theme#255]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="18.10"

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2

**Desktop environment:**

gnome

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**

Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
I can see the background through a gap in the toolbar. This only happens with the default theme for Firefox, I can't reproduce with light and dark themes.

![2018-12-17_17-55](https://user-images.githubusercontent.com/203078/50123281-bc6fcd80-0225-11e9-97c7-1c6ecbaf5c43.png)

**Steps to reproduce**

Open Firefox with the default theme enabled and using Pop-slim-dark GTK Theme.

**Expected behavior**

I shouldn't be able to see through my browser. 

**Behavior in Adwaita**

Can't reproduce.

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
Only occurs on dark theme. Probably related to a border color being set to something that won't end up working.

**Comment by isantop** [comment]
Negative on Dark theme. Actually, this happens on a wide variety of themes, including:

* elementary
* Pop
* Materia

Seems to work fine on:

* Adapta
* Adwaita
* Yaru

It also was tested and seems working fine on elementary OS 5.0 with the default theme.

**Comment by isantop** [comment]
I can't figure out which selectors we're using that are different from those other themes which don't experience this issue. It only happens when you have the tabs drawn in the titlebar and only apparently on GNOME 3.28.
