### ISSUE TITLE
[Feature request] xfmw4 theme

### ISSUE THREAD

**Issue by HelloMyDear** [pop-os/gtk-theme#263]
I know that this theme is made for the GNOME shell, but it's beautifully with XFCE. The only issue it has, it's that it don't have a theme for the window. That would be a nice addiction.

**Comment by jackpot51** [comment]
It is unlikely we would get to this, but we are open to pull requests

**Comment by malysps** [comment]
I've made a simple Xfwm theme matching Pop-dark GTK theme, it's here:
https://www.opendesktop.org/p/1299758/
