### ISSUE TITLE
Squashed QSpinBox in FreeCAD 0.18 dev

### ISSUE THREAD

**Issue by joelgraff** [pop-os/gtk-theme#265]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2
  Version table:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**
GNOME

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**
/*
 * Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0
 * Copyright 2017-2018 System76, Inc.

**Related Application and/or Shell theming (or name of widget)**
FreeCAD Qt5 QSpinBox

**Actual issue**
QSpinBox is squashed vertically.  Resizing dialog does not stretch QSpinBox

**Steps to reproduce**
Download latest FreeCAD 0.18 developer AppImage (PyQt5 Conda version)
Start FreeCAD
Create a new document
Switch to Sketcher workbench
Create a new sketch
QSpinBox under "offset" label is vertically squashed.

**Expected behavior**
QSpinBox should not be vertically squashed. :)

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

![screenshot from 2019-01-23 18-31-15](https://user-images.githubusercontent.com/3495498/51646431-1870f480-1f3e-11e9-859e-057c8904bd81.png)
![screenshot from 2019-01-23 18-31-55](https://user-images.githubusercontent.com/3495498/51646437-1c9d1200-1f3e-11e9-963d-01b1f95f9fa1.png)

**Comment by wood-galaxy** [comment]
Same problem here with another os (ubuntu budgie with pucillo theme). I have no problem with xubuntu with numix theme.
Some notes :
Problem appear with the official freecad stable ppa (version 0.18.1)
Problem is gone if you select a style sheet other than "No style sheet" (in Edit > Preferences... > General > General tab > Style sheet ).

**Comment by isantop** [comment]
Closing this very old non-GTK bug.
