### ISSUE TITLE
White line on top of screen with Dash to Panel extension, goes away with Adwaita theme

### ISSUE THREAD

**Issue by seanpmaxwell** [pop-os/gtk-theme#266]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

libgtk-3-0:
  Installed: 3.22.30-1ubuntu1
  Candidate: 3.22.30-1ubuntu1
  Version table:
 *** 3.22.30-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

Version of gnome that came preinstalled with my System76 Meerkat

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**

/*
 * Pop!_OS gtk-widgets Theme (The Pop!_GTK Theme) Version 4.0.0
 * Copyright 2017-2018 System76, Inc.

**Related Application and/or Shell theming (or name of widget)**

Gnome Dash to Panel Extension

**Actual issue**

When the extension is enabled a white line appears at the top of the screen. When I switch to the Adwaita theme the white line goes away. This is just started happening this morning. Everything else is up-to-date. White line gets covered up by windows. 

**Steps to reproduce**

Install Gnome Dash-to-Panel extension. Leave the default PopOS theme alone. 

**Expected behavior**
Should be no white line.

**Behavior in Adwaita**

Goes away. 

**Other Note (feature-request, question, etc...)**

**Comment by jackpot51** [comment]
I am seeing this on my three monitor desktop without dash to panel

**Comment by aden-young** [comment]
I'm seeing this on my two monitor setup using dash to dock, but the behaviour is the same when dash to dock is disabled.

**Comment by soroushahrari** [comment]
i have this issue since this morning on pop and pop-light theme
