### ISSUE TITLE
Firefox context menus don't respond to theme

### ISSUE THREAD

**Issue by weijia-cheng** [pop-os/gtk-theme#269]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2
  Version table:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

GNOME

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**

4.0.0

**Related Application and/or Shell theming (or name of widget)**

Firefox

**Actual issue**

Firefox context menus don't respond to theme

![screenshot from 2019-01-31 18-30-51](https://user-images.githubusercontent.com/1240463/52092694-5f866780-2586-11e9-930c-866e2a751147.png)

![screenshot from 2019-01-31 18-31-57](https://user-images.githubusercontent.com/1240463/52092730-83e24400-2586-11e9-85a1-e388b12cc4be.png)

**Steps to reproduce**

1. Open Firefox
2. Open a context menu, for example by right-clicking in the browser

**Expected behavior**

The context menu should respond to the theme

**Behavior in Adwaita**

![screenshot from 2019-01-31 18-29-13](https://user-images.githubusercontent.com/1240463/52092649-34037d00-2586-11e9-8f39-27ba554beb53.png)

![screenshot from 2019-01-31 18-32-32](https://user-images.githubusercontent.com/1240463/52092759-965c7d80-2586-11e9-90e9-17128ba3fd99.png)

**Comment by isantop** [comment]
Those screenshots appear to match the intended theming of menus in Firefox. Firefox doesn't use GTK directly, so some minor inconsistencies between its appearance and the look of GTK-native applications is to be expected.

**Comment by DanielJoyce** [comment]
You can set this in about:config. There are gtk options in there.

**Comment by isantop** [comment]
Closing this issue as we haven't gotten any information on it since March 23
