### ISSUE TITLE
Broken (ON/OFF) Buttons.

### ISSUE THREAD

**Issue by duhok1** [pop-os/gtk-theme#270]
**Distribution (run `cat /etc/os-release`):**

NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

3.24.4

**Desktop environment:**

Gnome 3.30.2

**Pop version (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```):**

Version 4.1.1

**Related Application and/or Shell theming (or name of widget)**

Gnome Tweaks

**Actual issue**

Default Adwaita theme button still present when selecting Pop theme. Photos below.

**Steps to reproduce**

Select Pop theme, open Gnome Tweaks, see switch (on/off) buttons.

**Expected behavior**

Clean, Pop only button theme.

![screenshot from 2019-02-03 12-44-11](https://user-images.githubusercontent.com/46654846/52180390-97262700-27b3-11e9-9cf2-3144434f19db.png)
![screenshot from 2019-02-03 12-44-33](https://user-images.githubusercontent.com/46654846/52180394-9d1c0800-27b3-11e9-851b-3efe357d9dee.png)
![screenshot from 2019-02-03 12-44-43](https://user-images.githubusercontent.com/46654846/52180397-a0af8f00-27b3-11e9-9172-ca207fe0464e.png)
![screenshot from 2019-02-03 12-44-33-b](https://user-images.githubusercontent.com/46654846/52180400-a3aa7f80-27b3-11e9-9006-f472979e6f39.png)

**Comment by isantop** [comment]
Did you install the Pop theme through git? If so, can you please send me the current revision you're currently at? You can get it by running `git rev-parse HEAD` from a terminal within your local copy of the git repo.

**Comment by brs17** [comment]
@isantop I actually saw this when looking at a 19.04 image yesterday. :thinking:

**Comment by isantop** [comment]
Yep, this is confirmed when running GTK 3.24.5 due to their new changes for Switches.
