### ISSUE TITLE
Desktop right-click menu has become completely transparent

### ISSUE THREAD

**Issue by OmarHussainX** [pop-os/gtk-theme#272]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2
  Version table:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**
Gnome

**Pop version (run ```apt policy pop-gtk-theme```):**
  Installed: 4.1.1~1549561776~18.10~20fd8b0
  Candidate: 4.1.1~1549561776~18.10~20fd8b0
  Version table:
 *** 4.1.1~1549561776~18.10~20fd8b0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main i386 Packages
        100 /var/lib/dpkg/status

**Related Application and/or Shell theming (or name of widget)**
Desktop right-click context menu

**Actual issue**
The desktop right-click menu is clear! Totally transparent. I'm referring to the menu that appears when right-clicking an empty area of the desktop, with entries such as: 'New folder, Paste, Select All, Keep aligned'

This issue appeared right after the pop-gtk theme was updated on my system, and is present in all variants (Slim, Slim Dark, etc.)

**Steps to reproduce**
Right click on a blank area of the desktop: the menu is transparent

**Expected behavior**
...that the menu match the rest of the theme

**Behavior in Adwaita**
Looks perfectly fine in Adwaita, and all other themes

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
I'm unable to replicate this on my machine. @brs17 Are you seeing this problem?

**Comment by OmarHussainX** [comment]
Thank you for looking into this - I'm surprised this isn't a widespread issue. I haven't modified the theme in any way, and I know with absolute certainty that it presented itself (on my machine anyway) right after the last update to the pop-gtk theme, just a few hours ago.

I've attached a screenshot:
![screenshot from 2019-02-08 15-38-54](https://user-images.githubusercontent.com/44478074/52510313-b6a8bf80-2bb8-11e9-81fa-2741079dfd1d.png)


Funny thing is, the update fixed an issue which I had been thinking of reporting... I took a screenshot of it, but didn't report it. It had to do with a button in a dialog window in Files being solid-filled, making the button text unreadable. I've attached a screenshot, _but this was fixed in the pop-gtk update that I installed a few hours ago_.
![bug_pop_theme](https://user-images.githubusercontent.com/44478074/52510299-aabcfd80-2bb8-11e9-8484-4bf40950fc5c.png)

**Comment by brs17** [comment]
@isantop I just did a fresh install and ran updates and do indeed see a transparent menu.

**Comment by codermcnoob** [comment]
I have the same / similar issue. When I right click on the desktop I can barely see the menu. The background for the menu seems to have become transparent. However when I right click in a program such as a web browser or file manager It's fine.


![screenshot from 2019-02-09 12-23-45](https://user-images.githubusercontent.com/47476045/52520860-7c95f700-2c66-11e9-9089-733572fda758.jpg)

**Comment by cata0309** [comment]
I have the same issue, did you solve the problem? Help me please

**Comment by cata0309** [comment]
Any solution ?

**Comment by aden-young** [comment]
Can confirm I am seeing this issue as well, screenshot attached.
![transparent-right-click](https://user-images.githubusercontent.com/16015661/52542937-e2b08480-2df4-11e9-8ebb-6974b78bbed3.png)

**Comment by OMslaw04** [comment]
![pop_theme_ss](https://user-images.githubusercontent.com/34199072/52552843-95480d80-2e1c-11e9-96e2-ca8ee97c230f.png)
I've noticed this issue with POP theme only as shown above in the ss.

I tested with Mojave, Flat Remix theme and its working fine. 
![mojave_theme_ss](https://user-images.githubusercontent.com/34199072/52552846-96793a80-2e1c-11e9-8d81-4f468fe70195.png)

**Comment by cata0309** [comment]
Allready installed Windows 10 pro back, Pop Os is a battery drainer!

**Comment by wmutschl** [comment]
I disagree, Pop OS Battery consumption is great on my Dell XPS Precision 7520.

**Comment by cata0309** [comment]
I doubt that. Try windows 10 pro or any version for a week and you will definetely agree with me. Almost every linux distro has battery consumption problems, even if you install tlp tools or any other tools, your battery would still get consumed very fast.
Just make the little experiment and install windows 10 for a few days and use it on dual boot or something, not VM !
And to be honest, the battery percentage estimation is garbage, from 39% it growed to 40% and I was not charging my laptop at all.
I was really in to the Pop Os experience and I will come back to it when the most of the bugs are fixed, I know the bugs will not stop from appearing, that's how the things work !
I hope you understood me and take me as a friend, not an enemy. I would love to switch to linux, especially Pop os, but I must be patient for the major bugs to be fixed!
Have a great day !

**Comment by cata0309** [comment]
You should open the issue again, the bug is still present, even with the latest updates.

**Comment by OmarHussainX** [comment]
> I doubt that. Try windows 10 pro or any version for a week and you will definetely agree with me. Almost every linux distro has battery consumption problems, even if you install tlp tools or any other tools, your battery would still get consumed very fast.
> Just make the little experiment and install windows 10 for a few days and use it on dual boot or something, not VM !
> And to be honest, the battery percentage estimation is garbage, from 39% it growed to 40% and I was not charging my laptop at all.
> I was really in to the Pop Os experience and I will come back to it when the most of the bugs are fixed, I know the bugs will not stop from appearing, that's how the things work !
> I hope you understood me and take me as a friend, not an enemy. I would love to switch to linux, especially Pop os, but I must be patient for the major bugs to be fixed!
> Have a great day !

Interesting... I've only tried Pop!_OS on two machines (ThinkPad X1 Carbon and T580), but in both cases it surpasses Windows10 in every way:

- battery life!!
- performance (cool & quiet in linux, not so in Win10)
- workflow (esp. as related to keyboard-based window management & virtual desktops)
- UI (Win10's user interface is not unified, with conflicting design styles, icons, and is generally stale compared to Pop!_OS consistent and polished appearance)

**Many thanks to system76 for their efforts** - I hope Windows improves in the future.

_Oh, and my right-click desktop menu was fixed a few days ago with a theme update_ - I think the fix wasn't apparent until after I rebooted though.

**Comment by cata0309** [comment]
I think you are very lucky :)

mie., 20 feb. 2019, 06:25 Omar Hussain <notifications@github.com> a scris:
