### ISSUE TITLE
Some scaling option in gnome-control-center are illegible 

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#278]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.1-1ubuntu2

**Desktop environment:**
GNOME

**Pop version (run ```apt policy pop-gtk-theme```):**
4.1.3.....4908

**Related Application and/or Shell theming (or name of widget)**
gnome-control-center

**Actual issue**
In gnome-control-center, on the Devices->Displays tab, some of the scaling options are illegible.

On a fresh install of 18.10 it looks like the following:
![screenshot from 2019-02-21 15-36-23](https://user-images.githubusercontent.com/7460774/53207889-3a6b9e80-35f2-11e9-95ed-52274e7a2cf5.png)
![screenshot from 2019-02-21 15-36-33](https://user-images.githubusercontent.com/7460774/53207890-3a6b9e80-35f2-11e9-95e5-c3ffed3e3cef.png)

**Behavior in Adwaita**
All options are clearly legible.

**Comment by isantop** [comment]
It turns out that GNOME Control Center is setting the `.image-button` style class for those buttons, despite there not being any images and despite them in fact having labels with text. Since the styling is _technically_ correct for that style class (which doesn't appear in the context of this usage), this should probably be patched in GNOME Control Center.

**Comment by isantop** [comment]
We might be able to fix this without breaking other styling by checking for `:checked` state buttons.
