### ISSUE TITLE
Test Speakers dialog changes size when testing speaker

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#279]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 18.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.1-1ubuntu2

**Desktop environment:**
GNOME

**Pop version (run ```apt policy pop-gtk-theme```):**
4.1.3.....4908

**Related Application and/or Shell theming (or name of widget)**
gnome-control-center

**Actual issue**
On the pop-up window that appears after selecting the "Test Speakers" button, the pop-up window changes size when selecting one of the speakers to test. While screenshots are attached, this is most easily noticed by recreating the issue on a local machine.

![screenshot from 2019-02-21 15-38-06](https://user-images.githubusercontent.com/7460774/53208739-1a89aa00-35f5-11e9-954f-8a2ec9a73a9f.png)
![screenshot from 2019-02-21 15-38-08](https://user-images.githubusercontent.com/7460774/53208740-1a89aa00-35f5-11e9-8c22-1f78b53b3525.png)

**Steps to reproduce**
Select the "Test Speakers" button at the bottom right of the Sound tab in gnome-control-center. Then select "Test". Notice that the window changes size.

**Expected behavior**
Window does not change size on button press.

**Behavior in Adwaita**
Window does not change size.

**Comment by isantop** [comment]
@brs17 Have you been able to test if this happens on 18.04 as well?

**Comment by brs17** [comment]
t@isantop This does not happen in 18.04.

**Comment by isantop** [comment]
This issue does not occur on 18.04, and the new theme does not exhibit this behavior in 19.10. Thus, this is being closed.
