### ISSUE TITLE
Window controls are styled differently depending on if they are in titlebars or headerbars.

### ISSUE THREAD

**Issue by DanyGee** [pop-os/gtk-theme#280]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```
**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
```
libgtk-3-0:
  Installed: 3.24.1-1ubuntu2
  Candidate: 3.24.1-1ubuntu2
  Version table:
 *** 3.24.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status
```
**Desktop environment:**

`Gnome 3.30.1`

**Pop version (run ```apt policy pop-gtk-theme```):**
```
pop-gtk-theme:
  Installed: 4.1.3~1550077073~18.10~dac4908
  Candidate: 4.1.3~1550077073~18.10~dac4908
  Version table:
 *** 4.1.3~1550077073~18.10~dac4908 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main i386 Packages
        100 /var/lib/dpkg/status
```
**Related Application and/or Shell theming (or name of widget)**
`Terminal - showing wrong buttons background on click`
`Nautilus - not showing wrong buttons background on click`

**Actual issue**
Some apps show inproper window control buttons background (on click) not matching the titlebar color.
`Terminal (Mailspring, Telegram) for example shows it.`
`Nautilus (Calculator, Settings) doesn't.`

**Steps to reproduce**
`Open terminal and nautilus and click (and hold) on the title bar buttons and observe their background.`

**Expected behavior**
`All opened apps should follow the default theme without broken titlebar buttons on click.`

**Behavior in Adwaita**
`Correct - no broken buttons.`

**System**
```
OS: Pop!_OS 18.10 x86_64 
Kernel: 4.18.0-15-generic 
Uptime: 2 hours, 2 mins 
Packages: 1950 (dpkg) 
Shell: bash 4.4.19 
Resolution: 3840x2160 (200% scaling)
DE: GNOME 3.30.1 
WM: GNOME Shell 
WM Theme: Pop 
Theme: Pop [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-6700K (8) @ 4.200GHz 
GPU: NVIDIA GeForce GTX 1080 (Driver Version: 410.78)
Memory: 5364MiB / 32101MiB 
```
**Screenshots**
Terminal
![terminal](https://user-images.githubusercontent.com/26818551/53325309-55385e80-38e3-11e9-9586-7ea28124d2b6.jpg)
Nautilus
![nautilus](https://user-images.githubusercontent.com/26818551/53325322-5b2e3f80-38e3-11e9-8230-fc5ebd400ed9.jpg)

**Comment by DanyGee** [comment]
Bug still present in 19.04. :bug:

**Comment by DanyGee** [comment]
Issue still present in Telegram, Mailspring, Discord, Simplenote (looks like its present in everything installed manually from *deb file or an appimage).
I can confirm the issue is fixed in Terminal.
System updated today, checked after reboot.

**Comment by mmstick** [comment]
@DanyGee I don't think the stable repositories has the updated gtk-theme package yet. When a pull request is merged into the master branch, the build server will build the new changes for proposed. At a later point, we manually push the packages to the stable repos.
