### ISSUE TITLE
No selection highlight on Geary sidebar

### ISSUE THREAD

**Issue by bwat47** [pop-os/gtk-theme#283]
Wasn't sure if I should enter this as an issue with the Pop GTK theme, or with geary itself. It does behave as expected with Adwaita, so I'll start here.

**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

3.24.4-0ubuntu1

**Desktop environment:**

Gnome 3.30.2

**Pop version (run ```apt policy pop-gtk-theme```):**

4.1.3~1550077073~18.10~dac4908

**Related Application and/or Shell theming (or name of widget)**

Geary 0.13.3

**Actual issue**

The geary sidebar (that shows the listing of email folders on the left side) does not have any highlight color to indicate the selected folder when using the Pop GTK theme. See the attached screenshot (in this screenshot 'Outbox' is the selected folder)

![Screenshot from 2019-03-19 07-24-17](https://user-images.githubusercontent.com/1442520/54602718-cff32600-4a18-11e9-882f-a9ff1013871a.png)

**Steps to reproduce**

1. Open Geary
2. Select a folder

**Expected behavior**

There should be an orange highlight to indicate the selected folder (e.g. like how the nautilus sidebar behaves with the pop GTK theme).

**Behavior in Adwaita**

It works as expected in Adwaita (there's a blue highlight to indicate the selected folder).

**Comment by halfcutskeleton** [comment]
I can confirm that this bug affects me on two different computers using fresh install of Pop!_OS.

**Comment by bekips** [comment]
i can confirm both that the bug affects me, and that Adwaita works as expected.
