### ISSUE TITLE
White background with white text in deepin-terminal

### ISSUE THREAD

**Issue by rzrbld** [pop-os/gtk-theme#286]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
```
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
```
libgtk-3-0:
  Installed: 3.24.4-0ubuntu1.1
  Candidate: 3.24.4-0ubuntu1.1
  Version table:
 *** 3.24.4-0ubuntu1.1 500
        500 http://ru.archive.ubuntu.com/ubuntu cosmic-proposed/main amd64 Packages
        100 /var/lib/dpkg/status
     3.24.4-0ubuntu1 500
        500 http://ru.archive.ubuntu.com/ubuntu cosmic-updates/main amd64 Packages
     3.24.1-1ubuntu2 500
        500 http://ru.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
```

**Desktop environment:**
```
DE: GNOME 3.30.2 
```

**Pop version (run ```apt policy pop-gtk-theme```):**
```
pop-gtk-theme:
  Installed: 4.1.4~1554311930~18.10~4322172
  Candidate: 4.1.4~1554311930~18.10~4322172
  Version table:
 *** 4.1.4~1554311930~18.10~4322172 500
        500 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
        500 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main i386 Packages
        100 /var/lib/dpkg/status
```

**Related Application and/or Shell theming (or name of widget)**
```
WM: GNOME Shell 
WM Theme: Pop 
Theme: Pop [GTK2/3] 
Icons: Pop [GTK2/3] 
```

**Actual issue**
right sidebar in deepin-terminal appears with white (almost) background with white text on it, as shown below:
![image](https://user-images.githubusercontent.com/1006416/55614116-fb09a380-5794-11e9-9dfd-0a2eec0d92d2.png)

**Steps to reproduce**
0. switch to pop theme for Application or All elements in ```gnome-tweaks```
1. install deepin-terminal 
```
apt install deepin-terminal
```
2. click on hamburger icon at the top right corner of main window in deepin-terminal
3. in dropdown menu choose  ``` remote-management ```
4. look at remote management sidebar

**Expected behavior**
the text should be readable

**Behavior in Adwaita**
how it looks on default Yaru theme:
![image](https://user-images.githubusercontent.com/1006416/55614364-74a19180-5795-11e9-87d5-5b74221acf60.png)

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
It doesn't look like that's using the GTK theme, and while it does adapt based on the theme it's possible for it to misinterpret the theme and draw things incorrectly. 

I can't get the application to work at all for replication. Clicking on the menu button does not open any drop-downs regardless of which theme I have selected.

**Comment by rzrbld** [comment]
@isantop  thanks for response. deepin-terminal uses own themes, but sidebar background getting from gtk theme, as you can see there is no problems in yaru theme, and the few other themes that i've tested.

kind of wird that you can't click on hamburger icon, but you can try install all deps:
``` sudo apt-get install libatk1.0-0 libc6 libcairo-gobject2 libcairo2 libfontconfig1 libgdk-pixbuf2.0-0 libgee-0.8-2 libglib2.0-0 libgnutls30 libgtk-3-0 libice6 libjson-glib-1.0-0 libpango-1.0-0 libpangocairo-1.0-0 libpcre2-8-0 libreadline7 librsvg2-2 libsecret-1-0 libsm6 libstdc++6 libtinfo5 libwnck-3-0 libx11-6 libxext6 zlib1g lrzsz expect deepin-menu ``` and try again.

or you can build it from sources - just as described here ( https://github.com/linuxdeepin/deepin-terminal )
this problem reproduces on every version of deepin-terminal.

**Comment by rzrbld** [comment]
further investigating lead me that ```Pop-dark``` isn't affected:

![image](https://user-images.githubusercontent.com/1006416/55874368-d8afc580-5b9a-11e9-87d0-045e17c00162.png)

**Comment by rzrbld** [comment]
@isantop if problem with "hamburger" icon is still present try to:
```apt remove dde-qt5integration```

**Comment by milottit** [comment]
> further investigating lead me that `Pop-dark` isn't affected:
> 
> ![image](https://user-images.githubusercontent.com/1006416/55874368-d8afc580-5b9a-11e9-87d0-045e17c00162.png)
> 
> Theme	Bug is reproduced?
> Pop	
> Pop-dark	
> Pop-light	
> Yaru	
> Yaru-dark

Orchis theme is affected also

**Comment by milottit** [comment]
> @isantop if problem with "hamburger" icon is still present try to: `apt remove qt5dxcb-plugin dde-qt5integration`

If you are removing this libs, a lot of nice behaviors will disappear. What a pity :(

**Comment by rzrbld** [comment]
> If you are removing this libs, a lot of nice behaviors will disappear. What a pity :(
this is about bug reproducing and not about nice behaviors. But above it all - psss it's a 3yo bug
