### ISSUE TITLE
Nautilus: graphical glitch on new nautilus windows when animated pie-chart 

### ISSUE THREAD

**Issue by friimaind** [pop-os/gtk-theme#290]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
```
libgtk-3-0:
  Installed: 3.24.8-1ubuntu1
  Candidate: 3.24.8-1ubuntu1
  Version table:
 *** 3.24.8-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Desktop environment:**
`GNOME`

**Pop version (run ```apt policy pop-gtk-theme```):**
```
pop-gtk-theme:
  Installed: 4.1.4~1555438800~19.04~185a5b6
  Candidate: 4.1.4~1555438800~19.04~185a5b6
  Version table:
 *** 4.1.4~1555438800~19.04~185a5b6 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main i386 Packages
        100 /var/lib/dpkg/status
```

**Related Application and/or Shell theming (or name of widget)**
nautilus

**Actual issue**
There's a graphical glitch when you create a new session of nautilus when there's a task running (like copy / compress...)

![image](https://user-images.githubusercontent.com/16322003/56428256-042f6000-62bf-11e9-8327-4bf712acb97d.png)

**Steps to reproduce**
- open nautilus
- copy a large file or compress a large file to show the pie chart loading
- open a new windows of nautilus (CTRL+N)

**Expected behavior**
no graphical glitch

**Behavior in Adwaita**
It does not affect other themes

**Comment by isantop** [comment]
I can personally replicate graphical glitches in that area when making large file copy operations with other themes, including Adwaita and Yaru. I don't believe this is specific to the Pop theme (though it may be more visible here due to our color choices).
