### ISSUE TITLE
arrow dropdown on nautilus search bar looks pretty out of place

### ISSUE THREAD

**Issue by bwat47** [pop-os/gtk-theme#294]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.04

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.8-1ubuntu1

**Desktop environment:**
Gnome 3.32

**Pop version (run ```apt policy pop-gtk-theme```):**
4.1.4~1556120984~19.04~2988243

**Related Application and/or Shell theming (or name of widget)**
Nautilus

**Actual issue**
With the Pop GTK theme, the dropdown menu icon on the nautilus search bar looks pretty strange. It doesn't look like it's properly a part of the search bar. 

This is a bit hard to explain, but I think the attached screenshot comparison vs adwaita makes it clear.

**Steps to reproduce**
Open Nautilus

Click the search icon
![adwaita](https://user-images.githubusercontent.com/1442520/57046613-215d1a80-6c3f-11e9-81d4-7c08447dbc1a.png)
![pop](https://user-images.githubusercontent.com/1442520/57046614-215d1a80-6c3f-11e9-8a33-5697215dcb62.png)

**Comment by trgeiger** [comment]
I've also noticed this. The rounded edges next to one another look odd. It seems like it should be more integrated into the dropdown, like in Adwaita.

**Comment by isantop** [comment]
New Styling:

![Screenshot from 2019-05-13 10-45-13](https://user-images.githubusercontent.com/5883565/57639013-3a819780-756c-11e9-8bd9-65908c3bd82c.png)

**Comment by bwat47** [comment]
I noticed another wonky looking theming issue with the nautilus search bar. I'm not sure if it's impacted by this fix or not, so I entered a separate issue: 302
