### ISSUE TITLE
Dark theme has an issue with menu items

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/gtk-theme#304]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

aaronhoneycutt@pop-os ~> cat /etc/os-release
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

aaronhoneycutt@pop-os ~> apt policy libgtk-3-0
libgtk-3-0:
  Installed: 3.24.8-1ubuntu1
  Candidate: 3.24.8-1ubuntu1
  Version table:
 *** 3.24.8-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

GNOME 3.32

**Pop version (run ```apt policy pop-gtk-theme```):**

aaronhoneycutt@pop-os ~> apt policy pop-gtk-theme
pop-gtk-theme:
  Installed: 4.1.4~1557754575~19.04~952b012
  Candidate: 4.1.4~1557754575~19.04~952b012
  Version table:
 *** 4.1.4~1557754575~19.04~952b012 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main i386 Packages
        100 /var/lib/dpkg/status

**Related Application and/or Shell theming (or name of widget)**

Dark Pop Theme

**Actual issue**

If you select a menu item in Setting or GNOME Tweaks then click away the background for the item doesn't come back until you click on it.

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**

Does not happen in Adwaita.

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
Appears to be fixed in #307
