### ISSUE TITLE
GNOME Todo: Pop Variant: Difficult to Distinguish Delete Button

### ISSUE THREAD

**Issue by mmstick** [pop-os/gtk-theme#305]
Seems to be a quirk in GNOME ToDo's styling. The color of the "Rename" and "Delete" buttons when selecting task lists remains the same in both the dark and light theme, making the buttons readable on the dark theme, but less readable in a lighter theme.

![Screenshot from 2019-05-30 13-59-45](https://user-images.githubusercontent.com/4143535/58660740-5ebad380-82e3-11e9-82e5-df452bbdc2fb.png)

**Comment by isantop** [comment]
This also seems fixed in #307

**Comment by mmstick** [comment]
The light theme is fixed, though there seems to be an issue with the dark theme.

![Screenshot from 2019-06-13 16-37-52](https://user-images.githubusercontent.com/4143535/59472144-bf293500-8dfa-11e9-8174-b6f8ebaa4ebe.png)

**Comment by JamesSwift** [comment]
The same issue exists with Gnome Contacts, where the delete button is basically invisible. Does this PR fix contacts too?

![image](https://user-images.githubusercontent.com/2080205/59529670-8d3ad000-8ed9-11e9-9be7-b91164ccc715.png)

**Comment by mmstick** [comment]
Yes, it fixes Contacts as well.

**Comment by mmstick** [comment]
@JamesSwift 

![Screenshot from 2019-06-14 12-32-46](https://user-images.githubusercontent.com/4143535/59530333-8c397c80-8ea0-11e9-964b-6e8b3d8fc31a.png)
![Screenshot from 2019-06-14 12-32-36](https://user-images.githubusercontent.com/4143535/59530334-8c397c80-8ea0-11e9-8634-6bcbdacb1a25.png)

**Comment by JamesSwift** [comment]
Amazing! This bug drove me nuts for about 10 minutes until I found the button after searching google. Thanks for all the hard work!

**Comment by mmstick** [comment]
You'll have the update soon, but if you'd like to try it early, you can fetch it from the staging repo: http://apt.pop-os.org/staging/dark-theme-colors/pool/disco/gtk-theme/pop-gtk-theme_4.2.0~1560532325~19.04~32f29ac_all.deb

**Comment by JamesSwift** [comment]
Awesome! I was searching around for a way to test it without compiling, but couldn't find one. How can I find the right .deb for other PRs in the future, if I want to try them out?

**Comment by mmstick** [comment]
The official way is to add the staging repo through the `apt` script from the `pop` repo.

```sh
git clone https://github.com/pop-os/pop
./pop/scripts/apt add ${name_of_branch}
sudo apt upgrade
```

All branches on our GitHub repositories automatically generate staging repositories with every commit. So if you know the branch name of a PR, you can add it to test it out.

**Comment by JamesSwift** [comment]
Thanks.
