### ISSUE TITLE
Broken drop-down bar in Epiphany/Gnome Web in full-screen

### ISSUE THREAD

**Issue by v-marinkov** [pop-os/gtk-theme#306]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
libgtk-3-0:
  Installed: 3.24.8-1ubuntu1
  Candidate: 3.24.8-1ubuntu1
  Version table:
 *** 3.24.8-1ubuntu1 500
        500 http://it-mirrors.evowise.com/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status

**Pop version (run ```apt policy pop-gtk-theme```):**

  Installed: 4.1.4~1557754575~19.04~952b012
  Candidate: 4.1.4~1557754575~19.04~952b012
  Version table:
 *** 4.1.4~1557754575~19.04~952b012 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main i386 Packages
        100 /var/lib/dpkg/status

**Actual issue**

Enter full-screen mode in Epiphany with F11. The drop-down bar and buttons are all transparent and illegible. Only the url field is not transparent. This does not happen on any other theme but the Pop variants.

**Behavior in Adwaita**
The drop-down bar in full-screen is perfectly consistent with the normal bar.

**Other Note (feature-request, question, etc...)**

Also, the blue loading bar on the url (not in full-screen) has poor visibility.

**Comment by isantop** [comment]
This issues appears to be fixed in #307
