### ISSUE TITLE
feedreader: GtkSearchEntry in GtkHeaderBar

### ISSUE THREAD

**Issue by mmstick** [pop-os/gtk-theme#309]
This may also be an issue. The search entry in a header bar does not have padding.

![Screenshot from 2019-06-06 10-10-54](https://user-images.githubusercontent.com/4143535/59048659-91b11a00-8843-11e9-94e9-db1a1b9514d1.png)

**Comment by isantop** [comment]
The large changes to the way padding is defined in upcoming PRs should fix issues like this.

**Comment by mmstick** [comment]
Indeed it is fixed
