### ISSUE TITLE
Invalid color name in gtk.css

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/gtk-theme#311]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

Pop 19.04

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

**Desktop environment:**

GNOME 3.32

**Pop version (run ```apt policy pop-gtk-theme```):**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

Jun  7 00:14:23 pop-os firefox[7707]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:18:15 pop-os system76-driver[7994]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:27:52 pop-os gnome-control-c[8796]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:34:34 pop-os system76-driver[9547]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:44:17 pop-os firefox[10624]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:48:33 pop-os firefox[11182]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:49:02 pop-os firefox[11240]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:49:03 pop-os firefox[11402]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:49:03 pop-os firefox.desktop[2174]: (/usr/lib/firefox/firefox:11402): Gtk-WARNING **: 22:49:03.671: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:49:04 pop-os firefox[11465]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:49:04 pop-os firefox.desktop[2174]: (/usr/lib/firefox/firefox:11465): Gtk-WARNING **: 22:49:04.131: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:49:04 pop-os firefox[11554]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:49:57 pop-os firefox.desktop[2174]: (/usr/lib/firefox/firefox:11554): Gtk-WARNING **: 22:49:57.647: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:49:57 pop-os firefox[11711]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:57:46 pop-os firefox.desktop[2174]: (/usr/lib/firefox/firefox:11711): Gtk-WARNING **: 00:57:46.670: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:57:46 pop-os firefox[12631]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:59:04 pop-os firefox.desktop[2174]: (/usr/lib/firefox/firefox:12631): Gtk-WARNING **: 00:59:04.126: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 00:59:04 pop-os firefox[12849]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 01:02:10 pop-os geary[13207]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 01:02:10 pop-os WebKitWebProces[13229]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 01:09:04 pop-os firefox.desktop[2174]: (/usr/lib/firefox/firefox:12849): Gtk-WARNING **: 01:09:04.116: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 01:09:04 pop-os firefox[13989]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 01:19:04 pop-os firefox.desktop[2174]: (/usr/lib/firefox/firefox:13989): Gtk-WARNING **: 01:19:04.121: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 01:19:04 pop-os firefox[15138]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 01:19:18 pop-os org.gnome.Shell.desktop[2174]: # Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 01:26:02 pop-os firefox.desktop[2174]: (/usr/lib/firefox/firefox:15138): Gtk-WARNING **: 01:26:02.351: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Jun  7 01:26:02 pop-os firefox[15934]: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name

**Steps to reproduce**

Look at the logs that the system76-driver creates

**Expected behavior**

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
Fixed in #310
