### ISSUE TITLE
Updates break the Wacom One tablet driver

### ISSUE THREAD

**Issue by Dez1gner** [pop-os/gtk-theme#315]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop! _OS! 18.04

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.22.30-1ubuntu3

**Desktop environment:**
Gnome 3...

**Pop version (run ```apt policy pop-gtk-theme```):**
4.1.4~1560290633~18.04~f75e86a

**Related Application and/or Shell theming (or name of widget)**
input-wacom-0.43.0

**Actual issue**
Incoming updates to POP! Shop breaks the tablet driver.
This problem appeared about 2 months ago.
Only manual installation of the input-wacom driver helps.

**Steps to reproduce**
Update
Reboot PC

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
Is this related to the Pop_OS theme? That doesn't sound like something that the theme could break.
