### ISSUE TITLE
Applications lose theming on starting PopOS

### ISSUE THREAD

**Issue by anurag2361** [pop-os/gtk-theme#317]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**

libgtk-3-0:
  Installed: 3.24.8-1ubuntu1
  Candidate: 3.24.8-1ubuntu1
  Version table:
 *** 3.24.8-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status

**Desktop environment:**

GNOME

**Pop version (run ```apt policy pop-gtk-theme```):**

pop-gtk-theme:
  Installed: 4.1.4~1560290633~19.04~f75e86a
  Candidate: 4.1.4~1560290633~19.04~f75e86a
  Version table:
 *** 4.1.4~1560290633~19.04~f75e86a 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main i386 Packages
        100 /var/lib/dpkg/status

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

For some unknown reason, whenever i start my laptop, the application themes start in some Windows 98-ey appearance. I always have to open GNOME-Tweaks tool and select Pop theme in Applications menu of Appearance.

**Steps to reproduce**

1. Boot into Pop!_OS
2. Open any application.

**Expected behavior**

Applications should have Pop theme applied by default without any tweaking.

**Behavior in Adwaita**

Not tried yet.

**Other Note (feature-request, question, etc...)**

nil.

**Comment by isantop** [comment]
This doesn't appear to be an issue from the theme, but rather with something else causing problems. Does this continue to happen for you?

**Comment by anurag2361** [comment]
No. Actually it was my own fault as a script I made some time before kept changing the theme. Sorry for the inconvenience.
