### ISSUE TITLE
Radio button in terminal is difficult to see

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#324]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.11-1ubuntu1

**Desktop environment:**
GNOME

**Pop version (run ```apt policy pop-gtk-theme```):**
5.0.0...d3d09d6

**Related Application and/or Shell theming (or name of widget)**
terminal

**Actual issue**
As seen in the following screenshot, when highlighting the unselected radio button, it is very difficult to see the radio button outline. I found this radio button in `gnome-terminal` with two tabs open.
![radio_button](https://user-images.githubusercontent.com/7460774/65896602-bc7f2b00-e36a-11e9-9f03-a56982776514.png)

This may be the intended look/functionality. If that is the case feel free to close the issue.

**Comment by isantop** [comment]
Addressed in 3224cdf527a4c7959fc9c54450ede2d677d6f62c to merge once #322 is merged

**Comment by isantop** [comment]
Fixed with #322
