### ISSUE TITLE
[Shell] 19.10: GDM spinner overlaps with button when incorrect password is entered on HiDPI

### ISSUE THREAD

**Issue by leviport** [pop-os/gtk-theme#347]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
```
levi@pop-os:~$ apt policy libgtk-3-0 
libgtk-3-0:
  Installed: 3.24.11-1ubuntu1
  Candidate: 3.24.11-1ubuntu1
  Version table:
 *** 3.24.11-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Desktop environment:**
Gnome

**Pop version (run ```apt policy pop-gtk-theme```):**
```
pop-gtk-theme:
  Installed: 5.0.0~1570207623~19.10~69f31e7
  Candidate: 5.0.0~1570207623~19.10~69f31e7
  Version table:
 *** 5.0.0~1570207623~19.10~69f31e7 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
        100 /var/lib/dpkg/status
```

**Related Application and/or Shell theming (or name of widget)**
gdm3

**Actual issue**
The spinner overlaps with the Unlock button when an incorrect password is entered.
![IMG_20191007_143033](https://user-images.githubusercontent.com/13512097/66348747-80246f80-e914-11e9-88d8-43d65630776f.jpg)

**Steps to reproduce**
Enter an incorrect password at the login screen

**Comment by isantop** [comment]
This also occurs with the Adwaita theme as well, so I'm marking this an upstream issue
