### ISSUE TITLE
Pop!_Shop: Program description text has different color text box

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#360]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.12-1ubuntu1

**Desktop environment:**
GNOME

**Pop version (run ```apt policy pop-gtk-theme```):**
5.0.0-1570566474-19.10-472b0cf

**Related Application and/or Shell theming (or name of widget)**
Pop!_Shop

**Actual issue**
On an application page, the text description textbox is shaded with a different color than the rest of the background.

![footer_low_vis](https://user-images.githubusercontent.com/7460774/66779889-9c805900-ee8c-11e9-8786-138c0a592388.png)

**Expected behavior**
The background of this textbox is the same color as the rest of the application.

**Comment by isantop** [comment]
These are simply picking up the styling of the textview class, without using an appropriately colored container class. This should be styled out in the Pop_Shop application.css
