### ISSUE TITLE
Highlighted text has really dark inverted colors

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#361]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.12-1ubuntu1

**Desktop environment:**
GNOME

**Pop version (run ```apt policy pop-gtk-theme```):**
5.0.0-1570566474-19.10-472b0cf

**Related Application and/or Shell theming (or name of widget)**
Firefox 69.0.3

**Actual issue**
When highlighting text that is on a different colored background, the highlight inverts the colors which looks jarring and out of place especially switching colors in one selection.

![highlight](https://user-images.githubusercontent.com/7460774/66781120-be2f0f80-ee8f-11e9-90c9-0877408a31cd.png)

So far, this issue seems limited to Firefox as this issue does not happen in Chromium.

**Comment by isantop** [comment]
I can't seem to replicate this in cbbf790:

![Screenshot from 2019-10-15 10-29-50](https://user-images.githubusercontent.com/5883565/66850957-081f0080-ef37-11e9-82a4-216ac08f3ab9.png)

Running firefox `69.0.3+build1-0ubuntu1`

**Comment by brs17** [comment]
> I can't seem to replicate this in [cbbf790](https://github.com/pop-os/gtk-theme/commit/cbbf79064ef358acf7284397ebf095618eb861cc):
> 
> ![Screenshot from 2019-10-15 10-29-50](https://user-images.githubusercontent.com/5883565/66850957-081f0080-ef37-11e9-82a4-216ac08f3ab9.png)
> 
> Running firefox `69.0.3+build1-0ubuntu1`

Maybe try on a fresh install?  I was able to see the issue on a fresh install on a Darter Pro, fresh install of my orxp1, Tim's leow9-w, and Levi's oryp3.

**Comment by isantop** [comment]
Even in cbbf790?

**Comment by isantop** [comment]
Also, would it be possible to try it in a fresh profile without any browser extensions enabled? If this is limited to Firefox, then I'm doubtful this is something the theme is doing (especially since it only seems to affect the code blocks there with different background colors). 

You can try a different profile non-destructively by doing `mv ~/.mozilla ~/.mozillabackup` and relaunching Firefox. When you want to restore your own profile, do `rm -r ~/.mozilla && mv ~/.mozillabackup ~/.mozilla`

**Comment by brs17** [comment]
@isantop I am able to replicate this on a fresh install of 19.10 (before and after running updates).

**Comment by brs17** [comment]
Also reproducible on a fresh install on thelio-major-r2.

**Comment by isantop** [comment]
@brs17 This appears to be a firefox bug related to using black as the text color for selected text. It automatically tries to ensure contrast by inverting the color of the selection. I can "fix" this issue by making the selected text color white, which is not contrast-compliant. As such, I think we cannot fix this issue in the theme without compromising the appearance of the theme.
