### ISSUE TITLE
Thoughts regarding: Alt+Tab menu

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#362]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.12-1ubuntu1

**Desktop environment:**
GNOME

**Pop version (run ```apt policy pop-gtk-theme```):**
5.0.0-1570566474-19.10-472b0cf

**Related Application and/or Shell theming (or name of widget)**
GNOME Shell

**Thoughts**
The following are the thoughts I have regarding the <kbd>Alt</kbd>+<kbd>Tab</kbd> menu. Some or all of these may be invalid.

- The <kbd>Alt</kbd>+<kbd>Tab</kbd> menu is currently quite dark for the non-dark theme.
- Since the menu has some transparency, it potentially makes the text more difficult to read. Related, I find the text changing color a little jarring/odd.
![Screenshot from 2019-10-14 10-05-06](https://user-images.githubusercontent.com/7460774/66783757-d99d1900-ee95-11e9-93a3-42a077e8ce85.png)

**Comment by isantop** [comment]
@brs17 Given the lack of feedback we've seen about this current setup, and in the interest of keeping our delta against our upstream codebase small, I think it would be a good idea to keep the current design and possibly revisit for 20.04.
