### ISSUE TITLE
Libreoffice menu bar low contrast

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#363]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.12-1ubuntu1

**Desktop environment:**
GNOME

**Pop version (run ```apt policy pop-gtk-theme```):**
5.0.0-1570566474-19.10-472b0cf

**Related Application and/or Shell theming (or name of widget)**
libreoffice

**Actual issue**
When selecting a menu item in any of the applications within the Libreoffice suite, the menu item is highlighted in a color which only has a 2.3:1 contrast ratio.

![Screenshot from 2019-10-14 11-19-12](https://user-images.githubusercontent.com/7460774/66785011-39e18a00-ee99-11e9-8740-c9c3ed9380b8.png)
NOTE: The screenshot does not show the expanded menu, but it does appear when selecting the menu item.

**Comment by isantop** [comment]
On my machine, the menu item background in LO Writer is #63B1BC (Light-mode normal blue) and the text is #000, which gives a contrast ratio of 8.5:1. 

Running commit 05b939a

**Comment by brs17** [comment]
> On my machine, the menu item background in LO Writer is #63B1BC (Light-mode normal blue) and the text is #000, which gives a contrast ratio of 8.5:1.
> 
> Running commit [05b939a](https://github.com/pop-os/gtk-theme/commit/05b939a91ac3e11104cd13b76a6f6d4dfe23a491)

Well I am unable to get that off of a screenshot, but after examining 19.04, this does not seem to be much of an issue.
