### ISSUE TITLE
Pop!_Shop: Download text has strange background color

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#364]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 19.10

**Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```):**
3.24.12-1ubuntu1

**Desktop environment:**
GNOME

**Pop version (run ```apt policy pop-gtk-theme```):**
5.0.0-1570566474-19.10-472b0cf

**Related Application and/or Shell theming (or name of widget)**
Pop!_Shop

**Actual issue**
When downloading a program from the Pop!_Shop, the "Downloading" text next to the progress bar has an odd, out of place, background which is different from the surrounding background.
![Screenshot from 2019-10-14 11-30-12](https://user-images.githubusercontent.com/7460774/66785121-86c56080-ee99-11e9-98a7-158c38444976.png)

**Comment by isantop** [comment]
Part of this will require styling in the application.css itself, since it needs to have the text color set according to the application style.
