### ISSUE TITLE
19.10: Grab handles for rearranging list items are low contrast

### ISSUE THREAD

**Issue by leviport** [pop-os/gtk-theme#366]
**Describe the problem:**
The six-dot grabbing areas on the left sides of list items are low contrast in light and dark modes.

![g-c-c-low-contrast-grabbers](https://user-images.githubusercontent.com/13512097/66849883-f3416d80-ef34-11e9-9b36-239955c39621.png)
![g-c-c-low-contrast-grabbers-dark](https://user-images.githubusercontent.com/13512097/66849895-f5a3c780-ef34-11e9-9ed2-90b2c6e9b40a.png)

**Steps to reproduce:**
A good example of these grabbers is in gnome-control-center in the "Search" category.

**Distribution:**
Pop!_OS 19.10

**Pop version:**
```
system76@pop-os:~$ apt policy pop-gtk-theme 
pop-gtk-theme:
  Installed: 5.0.0~1570998216~19.10~cbbf790
  Candidate: 5.0.0~1570998216~19.10~cbbf790
  Version table:
 *** 5.0.0~1570998216~19.10~cbbf790 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by isantop** [comment]
They're a bit lighter than our base themes, I'll look at adjusting these.

**Comment by isantop** [comment]
These are hardcoded to use `@borders`, even though they aren't borders. Oh well...
