### ISSUE TITLE
gnome-terminal: scroll bar is very low contrast

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#369]
**Describe the problem:**
The vertical scroll bar in gnome-terminal is practically invisible due to being only a slightly different shade than the background of the terminal itself.

**Distribution:**

Pop!_OS 19.10

**Pop version:**

5.0.0-1570998216-19.10-cbbf790

**Comment by isantop** [comment]
Not sure where that got introduced, it's definitely different on Yaru and Adwaita.

**Comment by isantop** [comment]
This is very odd. The Pop and Adwaita `_common.scss` files differ by only 9 changes, none of which relate to scrollbars.

**Comment by isantop** [comment]
Got it
