### ISSUE TITLE
Upgrading to 19.10 with a `*-slim` or `*-light` will result in Adwaita theme

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#385]
**Describe the problem:**
When running an update from 19.04 to 19.10 with a pop-*-{light,slim} theme installed, since 19.10 does not offer slim or light themes, the theme defaults to Adwaita.

This will probably be fixed in https://github.com/pop-os/default-settings/ by parsing out light/slim.

**Comment by jackpot51** [comment]
Addressed in https://github.com/pop-os/default-settings/commit/cca6893c921983a078a92f21794bc908dd687ad8
