### ISSUE TITLE
`render-assets` Scripts do not render all assets.

### ISSUE THREAD

**Issue by AAnzel** [pop-os/gtk-theme#386]
**Describe the problem:**

When trying to compile the gtk theme from source and rerender all assets with the provided scripts, some assets are not rendered, which produces an error while building with meson. It is possible that I'm not doing something properly, therefore it would be beneficial to create [HACKING.md](https://github.com/pop-os/gnome-shell-theme/blob/master_bionic/HACKING.md) like tutorial. This is a minor feature with low priority, but it could make a slightly better documentation.

**Steps to reproduce:**
1. Change certain colors in .scss and gtkrc files.
2. Render assets using provided scripts.
3. Build project using provided instruction in README.md

**Distribution:**

PRETTY_NAME="Pop!_OS 19.10"

**Pop version:**

Installed: 5.0.0\~1571333736\~19.10~d7e5e73
Flatpak not installed

Edit: grammar

**Comment by isantop** [comment]
The fact that the scripts do not render all assets is a bug, and that should be fixed. 

That said, the changes you're describing don't require re-rendering any of the assets. You only need to do that when you make changes to the assets.svg files.

**Comment by AAnzel** [comment]
OK, could you then possibly help me with something?
Before, in Pop 19.04, when I wanted to replace orange accent color with a red one, I would change some orange hex values and re-render assets. That would in exchange produce, for instance, red close buttons, red highlights etc. Should I change this flow for eoan release?
All I need is changing orange and teal accent colors, so that the theme is according to my custom colored hardware, without losing Pop-specific features and design.
