### ISSUE TITLE
Black line as divisor in applications with split headerbar

### ISSUE THREAD

**Issue by pedrofleck** [pop-os/gtk-theme#392]
**Describe the problem:**

![Captura de tela de 2019-10-25 16-05-00](https://user-images.githubusercontent.com/761321/67616682-f8fb4680-f7b1-11e9-884a-1f472be06cc9.png)
I don't know if this is by design, since there is an old (#133) bug report that supposedly fixed it, but every app that has a split headerbar show a black line as a divisor, Adwaita has a much more subtle divisor that is not so distracting.

**Steps to reproduce:**
1. Open any application with a split headerbar, like Contacts or Tweaks.

**Distribution:**
Pop!_OS 19.10

**Pop version:**
5.0.0 ~1571333736 ~19.10 ~d7e5e73

**Comment by isantop** [comment]
This is something we probably inherited through Yaru, which uses much darker headerbars than Pop.
