### ISSUE TITLE
[Dark Theme] in Google Chrome - bad contrast in password / address autocomplete

### ISSUE THREAD

**Issue by pdanpdan** [pop-os/gtk-theme#407]
**Describe the problem:**
In Google Chrome, using GTK Theme with dark theme, the password and/or address autofill dialog is black on dark.

![Screenshot from 2019-11-12 00-15-19](https://user-images.githubusercontent.com/118764/68625853-c906af80-04e2-11ea-8856-e97bee6e22bd.png)

**Steps to reproduce:**
1. Chrome with GTK theme, dark
2. You need a site with username/password fields - make the password autocomplete dialog show
3. You can also reproduce on fields that try to autocomplete email/phone/address

**Distribution:**
Pop!_OS 19.10

**Pop version:**
5.0.0~1572998372~19.10~accb027

**Comment by isantop** [comment]
This appears to also be an issue in Adwaita.

**Comment by malvibra** [comment]
I have this issue with Aritim Dark too. It's a bit annoying.

**Comment by drewdavies** [comment]
Same deal, it's the only thing about my Pop!_OS install that doesn't seem polished.

**Comment by CorvetteCole** [comment]
Starting Chrome with the --force-dark-mode flag fixes the issue.
Using the chrome://flags Force Dark Mode does NOT fix it.
[As seen here](https://support.google.com/chrome/thread/17810964?hl=en)

Can confirm this fixes the issue for me

**Comment by matfantinel** [comment]
Chrome/ium had a regression and stopped identifying if Linux is using a light/dark theme. Please Star [the issue on their bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=998903) to pressure for a faster solution.

**Comment by isantop** [comment]
I believe this issue is fixed in the latest Chrome/Chromium releases upstream.
