### ISSUE TITLE
Theme doesn’t play well with unfocused  transparent windows

### ISSUE THREAD

**Issue by remcohaszing** [pop-os/gtk-theme#410]
**Describe the problem:**

Pop OS themes turns off transparency applications that don’t have focus. The screenshots below are taken using dark themes, but the issue also exists for the Pop OS light theme.

I have added 3 screenshots that show the following situation:

- Google Chrome is running behind all other applications
- Tilix is open running cmatrix in a transparent window
- Gnome Tweak Tools is open, either behind or in front of Tilix

Using Adwaita dark theme with Tilix on background

![image](https://user-images.githubusercontent.com/779047/69336768-93d72b80-0c5f-11ea-964a-c1321df65e74.png)

Using Pop OS dark theme with Tilix on background

![image](https://user-images.githubusercontent.com/779047/69336736-7f932e80-0c5f-11ea-9c6d-2fd9def3ab14.png)

Using Pop OS dark theme with Tilix on foreground

![image](https://user-images.githubusercontent.com/779047/69336828-b2d5bd80-0c5f-11ea-8727-68d07be128de.png)

**Steps to reproduce:**
1. ```
   sudo apt install tilix
   ```
2. Open Tilix
3. Open Preferences → Default (under Profiles) → Color
4. Configure transparency somewhere halfway

**Distribution:**

Pop!_OS 19.10


**Pop version:**

5.0.0~1573676952~19.10~8ddf0fc

**Comment by isantop** [comment]
This does not occur in Adwaita, but does in Yaru.

**Comment by isantop** [comment]
Found the issue in Yaru too, fixed here: https://github.com/ubuntu/yaru/pull/1547/
