### ISSUE TITLE
The Screen Shield displays the top panel when it should be transparent.

### ISSUE THREAD

**Issue by natrist** [pop-os/gtk-theme#423]
**Describe the problem:**

**Steps to reproduce:**
1. Lock the user session.
2. Notice the top panel is still showing a background color, even though it doesn't fit with the rest of the design.
3. Skip to the login screen.
4. Notice the top panel is now transparent.

![20200205_221826600_iOS](https://user-images.githubusercontent.com/3069681/73889106-e5de2500-483c-11ea-8ac5-e73f9154d827.jpg)

**Distribution:**

Pop!_OS 19.10

**Pop version:**

    5.0.0~1580846411~19.10~ba7b5fd

**Comment by isantop** [comment]
That appears to be correct per the design of the lock screen. Changing the design would mean carrying (and thus maintaining) a delta against the upstream GNOME theme, which is not desirable.
