### ISSUE TITLE
Calendar Event Titles unreadable on dark theme. Unable to change colors

### ISSUE THREAD

**Issue by ChrisWiegman** [pop-os/gtk-theme#425]
**Describe the problem:**
In Pop_OS 19.10, with Pop Dark mode enabled, it is impossible to read calendar event titles and changing colors for calendars in evolution doesn't help. When changing colors, most will result in the color block disappearing entirely.

![Screenshot from 2020-02-08 11-27-30](https://user-images.githubusercontent.com/394675/74088634-75b2e780-4a66-11ea-81bb-016b03e97ea9.png)

**Steps to reproduce:**
1. Switch to dark mode, view existing calendars
2. Try to change calendar colors in evolution to combat the bad calendar contrast

**Distribution:**
Pop!_OS 19.10

**Pop version:**
5.0.0~1580846411~19.10~ba7b5fd

**Comment by the1derer** [comment]
@isantop Any update on the fix? It is still present in 20.04. Thanks.

**Comment by ChrisWiegman** [comment]
Also popping in to ask about an update with 20.10 released

**Comment by kerrongordon** [comment]
Am having the same problem on 20.10

**Comment by isantop** [comment]
The problem appears to be much improve on 20.10, however, I see a couple changes that could be made to improve it further.
