### ISSUE TITLE
20.04 volume change sound repeats very slowly now

### ISSUE THREAD

**Issue by leviport** [pop-os/gtk-theme#426]
**Describe the problem:**
In 19.10, the volume adjustment indicator sound would repeat quickly if I held the volume up/down hotkeys. This provided an indication of how loud or quiet the volume was getting as I was adjusting it. Now the sound seems to only play at a rate of ~2 times per second, making the sound significantly less useful. This happens both when I hold volume up/down hotkeys, as well as if I repeatedly hit those hotkeys.

**Steps to reproduce:**
1. With volume hotkeys on a keyboard, change the volume quickly by holding the volume up/down keys, or rapidly hitting those keys.

**Distribution:**
Pop!_OS 20.04

**Pop version:**
`5.0.0~1581376555~20.04~ed888e9`

**Comment by isantop** [comment]
I think this is a change in GNOME, since this also occurs with the default GNOME Sound theme.

**Comment by leviport** [comment]
This is fixed now. Sound now repeats rapidly like it used to when changing volume.
