### ISSUE TITLE
Show password icon is too large

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#427]
**Describe the problem:**
With version 3.35.91 of GNOME in Pop!_OS 20.04, the login screen now has a toggle to show or hide the user's password in plaintext. The icon representing this feature is oddly large on this page. 

**Steps to reproduce:**
1. Select Enter when prompted with user to login with.
2. See large "eye" icon

**Distribution:**
Pop!_OS 20.04

**Pop version:**
2.1.0~1580335206~20.04~34ed946

**Comment by isantop** [comment]
This issue is being caused by the GNOME Shell Theme, not by the icon theme.
