### ISSUE TITLE
Lock screen error message is low contrast (at least with default wallpaper)

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#428]
**Describe the problem:**
When providing an incorrect password on the lockscreen (after the user has logged in), the error message: "Sorry, that didn't work. Please try again." is very difficult to read up against the default background(having upgraded from 19.10) for the lockscreen (https://github.com/pop-os/wallpapers/blob/master/original/kate-hazen-mort1mer.png).

**Steps to reproduce:**
1. Install 19.10
2. Upgrade to 20.04 with `pop-upgrade release upgrade systemd --force-next`
3. Login
4. Lock screen
5. Attempt to login with incorrect password.

**Distribution:**

Pop!_OS 20.04

**Pop version:**

Installed: 5.0.0~1581376555~20.04~ed888e9

**Comment by isantop** [comment]
@brs17 Can you grab a screenshot of what you're currently seeing? I think this is fixed in my 3.36 branch, but I want to be sure.

**Comment by brs17** [comment]
This is indeed fixed. Good work!
