### ISSUE TITLE
Activities search: Odd cursor overlay

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#429]
**Describe the problem:**
When selecting the Activities search bar, a cursor appears. This cursor is overlayed above the "Type to search" text. The cursor and `T` overlap oddly.

In previous Pop!_OS releases, the "Type to search" text disappears when the text box is selected and only the cursor is shown.

![activity_search](https://user-images.githubusercontent.com/7460774/76627603-e97e5f00-6500-11ea-9339-231a81809011.png)

**Steps to reproduce:**
1. Press the Super key.
2. With the cursor, select the search bar at the top (labeled "Type to search")

**Distribution:**
Pop!_OS 20.04

**Pop version:**
5.0.0~1581376555~20.04~ed888e9

**Comment by isantop** [comment]
This behavior also occurs with Adwaita, as well as the new version of the theme which supports 3.36. This leads me to believe this is a change in the way 3.36 draws entry widgets, and not something related to the theme.

![Screenshot from 2020-03-18 10-46-52](https://user-images.githubusercontent.com/5883565/76985544-fdadcc00-6905-11ea-92cb-a4d93eb5ab0e.png)

**Comment by isantop** [comment]
I can't seem to find any styling selectors which affect this issue. I think what's happening is the toolkit is drawing the placeholder as a text widget the same as it would for actual typed text. I don't think this is possible to change with CSS, and thus would need to be patched in the Shell code to actually have an effect.

**Comment by jackpot51** [comment]
I agree. This looks like a gnome-shell issue.

**Comment by isantop** [comment]
Closing here for now, since this isn't something the theme can fix. We can open a new issue or reopen and transfer this when we've decided how/if we'll handle this.
