### ISSUE TITLE
Application Menu: Misaligned "Open Window"

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#430]
**Describe the problem:**
Under the Application menu, the top option is often "Open Windows". Currently that text is not aligned properly and overlaps other text.

![application_menu](https://user-images.githubusercontent.com/7460774/76628365-36166a00-6502-11ea-90c3-35bfc9c63fc9.png)

**Steps to reproduce:**
1. Open graphical program
2. Select Application Menu

**Distribution:**
Pop!_OS 20.04

**Pop version:**

 5.0.0-1581376555-20.04-ed888e9

**Comment by isantop** [comment]
State as of ed888e9dd5de142cb899e362beedaf694594cc7e

![Screenshot from 2020-03-18 12-04-24](https://user-images.githubusercontent.com/5883565/76992933-a57cc700-6911-11ea-86b7-ccfb61c30ff2.png)

**Comment by leviport** [comment]
Confirmed! :+1:
