### ISSUE TITLE
Lock/login screen time and date are not themed

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#431]
**Describe the problem:**
Currently on the date and time on the lock/lockscreen are not themed as I would expect from upstream designs of GNOME 3.36. The date and time seem to be very small on the screen (especially since it is the only content on the screen).

**Distribution:**

Pop!_OS 20.04

**Pop version:**

5.0.0-1581376555-20.04-ed888e9

**Comment by isantop** [comment]
State as of ed888e9dd5de142cb899e362beedaf694594cc7e

![Screenshot from 2020-03-18 12-09-06](https://user-images.githubusercontent.com/5883565/76992871-84b47180-6911-11ea-83de-699746776fa1.png)

**Comment by leviport** [comment]
Confirmed!
