### ISSUE TITLE
Authentication pop-up missing proper themeing

### ISSUE THREAD

**Issue by brs17** [pop-os/gtk-theme#432]
**Describe the problem:**
The authentication pop-up that appears when launching a program that requires authentication is oddly formatted and misaligned.

![auth](https://user-images.githubusercontent.com/7460774/76638826-b6dd6200-6512-11ea-85f7-d60e1c66269c.png)

**Distribution:**
Pop!_OS 20.04

**Pop version:**
5.0.0-1581376555-20.04-ed888e9

**Comment by isantop** [comment]
State as of ed888e9dd5de142cb899e362beedaf694594cc7e

![Screenshot from 2020-03-18 12-05-21](https://user-images.githubusercontent.com/5883565/76992400-d3add700-6910-11ea-814a-c03930abb34d.png)

**Comment by leviport** [comment]
Confirmed, looks nice!
![Screenshot from 2020-03-18 13-00-48](https://user-images.githubusercontent.com/13512097/76997653-402cd400-6919-11ea-9b39-1d145d5beed8.png)
