### ISSUE TITLE
Do Not Disturb toggle does not appear

### ISSUE THREAD

**Issue by sleepforlife** [pop-os/gtk-theme#435]
as seen in the picture
toggle icon does not appear

distro fedora 32
gnome-shell 3.36
version :  pop-gnome-shell-theme_5.1.0~1584562463~20.04~36320d1

![Ekran Görüntüsü - 2020-03-20 22-27-06](https://user-images.githubusercontent.com/50239677/77199523-049d3000-6afa-11ea-9e88-dbb2dd1834ec.png)

sorry for poor eng.

**Comment by isantop** [comment]
This is fixed in the latest commits to master. Please try again with at least b1c540a3a65752e6d3600ad5939bcd3b46a20729 to solve this issue.

**Comment by tristan957** [comment]
@sleepforlife how did you install the theme in Fedora? Is there a repo or RPM I can find?
