### ISSUE TITLE
Toggle switches are missing in gnome-shell

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gtk-theme#440]
Toggle switches are missing in gnome-shell

**Comment by leviport** [comment]
@isantop are you certain this isn't just pop-shell? I see toggle switches everywhere else.

**Comment by isantop** [comment]
I'm not seeing them anywhere, and that error message is indicating a shell theme issue. It looks like the image paths were not updated to point at the GResource when the theme was switched to that.

**Comment by isantop** [comment]
I believe this is fixed by https://github.com/pop-os/gtk-theme/pull/441

**Comment by leviport** [comment]
Looks to be fixed here.
