### ISSUE TITLE
gtk and gnome-shell themes don't appear in gnome-tweaks

### ISSUE THREAD

**Issue by drakkan** [pop-os/gtk-theme#447]
After installing the deb for gtk and gnome-shell theme on Arch Linux the gtk theme is not listed in gnome-tweaks, for the shell theme only the dark variant is listed. 

I maintain these Arch Linux packages:

https://aur.archlinux.org/packages/pop-gtk-theme-bin
https://aur.archlinux.org/packages/pop-gnome-shell-theme-bin

they simply download and extract the precompiled deb files here:

http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-gtk-theme/pop-gtk-theme_5.2.0~1586289568~20.04~f35b83b_all.deb
http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-gtk-theme/pop-gnome-shell-theme_5.2.0~1586289568~20.04~f35b83b_all.deb

For the gtk theme the problem is the missing `gtk-3.0` directory inside `/usr/share/themes/Pop`, I fixed it with a symlink:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pop-gtk-theme-bin#n41

For the shell theme the problem is that `gnome-shell.css` and `gnome-shell-high-contrast.css` are missing in `/usr/share/themes/Pop/gnome-shell` while these css files can be found in `/usr/share/themes/Pop-dark/gnome-shell/` and so the dark variant is listed in gnome-tweaks.

I know that probably these packages works fine in Pop OS, that probably use a non standard way to find the themes. Do you mind to make them compatibile with other distro too? They worked well until the latest updates, thanks

**Comment by isantop** [comment]
This is probably due to a bug in the way we got builds working again with the updated `libsass` (see #446 ). It looks like the files in the `gtk-3.0` directory are being installed to the `gtk-3.20` directory (which doesn't cause problems with 3.20, as they're identical). 

The GNOME Shell issue will take some additional digging, as they are now being built with GResource files, which don't really have functional .css files.

**Comment by drakkan** [comment]
Thanks!

**Comment by drakkan** [comment]
this still does not work using the latest deb:

http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-gtk-theme/pop-gtk-theme_5.2.0~1587487811~20.04~c532d92_all.deb

no time to debug now

**Comment by isantop** [comment]
@drakkan That package version has not had the correct patches applied. The final portion of the fixed package version will be `f13d51a`

**Comment by drakkan** [comment]
@isantop yes, it works fine now, thanks!
