### ISSUE TITLE
Issues with active and inactive selection on both light and dark themes

### ISSUE THREAD

**Issue by openmindead** [pop-os/gtk-theme#452]
**Describe the problem:**
Screenshots are enough to see the problem:
![Screenshot from 2020-04-26 20-49-04](https://user-images.githubusercontent.com/36324977/80305658-63448080-8801-11ea-808f-6480ff9b9729.png)
![Screenshot from 2020-04-26 20-50-27](https://user-images.githubusercontent.com/36324977/80305661-663f7100-8801-11ea-87cb-a7bfdba5df15.png)

Description:
Light theme has an issue of inactive windows' text of selected items being too faint to read, dark theme is affected the other way round -- the text of active window's selected items is unreadable.
Not all apps are affected though, but anyway.

**Steps to reproduce:**
1. Boot 20.04 beta - you'll see it, install, reboot, update, reboot - no changes, still the same

**Distribution:**
Pop!_OS 20.04

**Pop version:**
`5.2.0~1587567562~20.04~b3f98df`

**Comment by leviport** [comment]
Thank you for the report! This issue is being tracked here: https://github.com/pop-os/gtk-theme/issues/373
