### ISSUE TITLE
Double title bar appears in Firefox

### ISSUE THREAD

**Issue by Thomasster** [pop-os/gtk-theme#455]
**Describe the problem:**

The main title bar should disappear but it stays, and double title bar appears in Firefox 

![Screenshot from 2020-05-01 11-09-24](https://user-images.githubusercontent.com/43536748/80795245-3ba43e00-8b9c-11ea-9c00-63a32f52719b.png)

**Steps to reproduce:**
1. Hamburger button
2. Customize...
3. uncheck "Title Bar"

**Distribution:**
 
Pop!_OS 20.04 LTS

**Pop version:**

Installed: 5.2.0\~1588203971\~20.04\~d94d9ec

**Comment by matfantinel** [comment]
This is actually an issue with Pop Shell extension, and should have been fixed already.

**Comment by Thomasster** [comment]
Indeed. The issue is now gone. Thanks.
