### ISSUE TITLE
Top bar no longer themed after 20.04 update

### ISSUE THREAD

**Issue by CyberneticCody** [pop-os/gtk-theme#457]
**Describe the problem:** After updating to Pop!_OS 20.04 today, the top bar in Gnome is no longer gray and is now a harsh black. Switching between the light and dark themes in settings does not seem to make a difference.
![Screenshot from 2020-05-01 14-19-33](https://user-images.githubusercontent.com/55600371/80830409-e4f82d80-8bb6-11ea-8eef-166f735af965.png)

**Steps to reproduce:**
1. Upgrade to Pop!_OS 20.04 from 19.10

**Distribution:** 
cat /etc/os-release | grep -i pretty_name : `PRETTY_NAME="Pop!_OS 20.04 LTS"`

**Pop version:**
apt policy pop-gtk-theme | grep -i installed : `5.2.0~1588203971~20.04~d94d9ec`
flatpack info org.gtk.Gtk3theme.Pop : `error: org.gtk.Gtk3theme.Pop/*unspecified*/*unspecified* not installed`

**Comment by Justin00015** [comment]
I also face this issue.
