### ISSUE TITLE
Building from source does not render all assets

### ISSUE THREAD

**Issue by AAnzel** [pop-os/gtk-theme#459]
**Describe the problem:**
When I remove assets from `gtk-theme/build/gtk/src/light/gtk-3.0/assets/` and then rerender them with the `render-assets.sh` an error occurs while building:

`gtk/src/light/gtk-3.0/meson.build:177:6: ERROR: Resource "assets/slider-horz-scale-has-marks-above-backdrop-dark.png" listed in ...`.

**Steps to reproduce:**
1. Remove all assets from `gtk-theme/build/gtk/src/light/gtk-3.0/assets/`
2. Rerender them with the `gtk-theme/build/gtk/src/light/gtk-3.0/render-assets.sh`

**Distribution:**
PRETTY_NAME="Pop!_OS 20.04 LTS"

**Pop version:**
Installed: 5.2.0~1588203971~20.04~d94d9ec
error: org.gtk.Gtk3theme.Pop/*unspecified*/*unspecified* not installed

**Comment by isantop** [comment]
You should not make modifications to the `/build` directory as this is managed automatically by meson and ninja. Instead, you should modify the master asset file in `gtk/src/light/gtk-3.20` and then clear the assets from `gtk/src/light/gtk-3.20/assets` and use the `gtk/src/light/gtk-3.20/render-assets.sh` to re-render them.

**Comment by AAnzel** [comment]
Thank you for your clarification!
