### ISSUE TITLE
Screen lock after update

### ISSUE THREAD

**Issue by AllizomFoxfire** [pop-os/gtk-theme#461]
**Describe the problem: After performing the latest updates, I can no longer lock the screen.**

**Steps to reproduce:**
1.  Install Pop.
2.  Install updates.
3.  Restart.

**Pop version: 20.04**

**Comment by leviport** [comment]
Hmm, I've not seen this happen. Are you trying to lock the screen from the top-right system menu option or the <kbd>Super</kbd> + <kbd>Esc</kbd> hotkey?

**Comment by AllizomFoxfire** [comment]
Trying to lock with the menu. Lock is there after install, but after the
updates it disappears. It also no longer locks after it suspends or dims
the screen.

**Comment by leviport** [comment]
So the actual lock button disappears out of the menu? Have you rebooted since installing the updates? Does the <kbd>Super</kbd> + <kbd>Esc</kbd> hotkey work?

**Comment by AllizomFoxfire** [comment]
Yes, as you can see from the snip below "Lock" is gone. Also, Super + Esc no longer work either.  This happens on both of my machines with completely dissimilar hardware.



![2020-06-17_19-15](https://user-images.githubusercontent.com/67071878/84960373-71ab6c00-b0cf-11ea-9f3d-4159993af7be.png)

**Comment by AllizomFoxfire** [comment]
I found the setting that restored screen lock on my devices. 

gsettings set org.gnome.desktop.lockdown disable-lock-screen false

You can see that it also added the entry back to the menu. It also restored Super + Esc.

![Screenshot-20200701081109-3840x1080](https://user-images.githubusercontent.com/67071878/86243609-ac53e080-bb74-11ea-8753-fead948c628f.png)
