### ISSUE TITLE
"Pop" not a theming option in Gnome Tweak Tools

### ISSUE THREAD

**Issue by battata** [pop-os/gtk-theme#463]
"Pop" is not an option under applications theming in Gnome Tweak Tools. The other theming options are OK, only applications has the problem.
![Captura de pantalla de 2020-06-23 02-24-29](https://user-images.githubusercontent.com/24719702/85364263-217e4080-b4f9-11ea-9533-4a08c98f4219.png)
![Captura de pantalla de 2020-06-23 02-25-01](https://user-images.githubusercontent.com/24719702/85364266-2216d700-b4f9-11ea-9707-93f315db2747.png)

**Distribution:**
Ubuntu 20.04 LTS

Added and installed pop-theme from ppa:system76/pop

**Comment by erlonpr** [comment]
Same thing happened to me.

I'm using the **Ubuntu 20.04 LTS** distribution.

**Comment by rtud** [comment]
Same here, under Ubuntu 20.04 LTS.

**Comment by isantop** [comment]
Note: Adding the `system76/pop` PPA on Ubuntu may cause breakage of the Ubuntu installation and is not recommended. It's better to install Pop directly instead of adding this PPA.

What is the package version of the GTK Theme currently installed? `apt policy pop-gtk-theme`

**Comment by isantop** [comment]
Closed for inactivity while blocked.
