### ISSUE TITLE
Improve Nautilus path bar

### ISSUE THREAD

**Issue by otavioschwanck** [pop-os/gtk-theme#465]
![image](https://user-images.githubusercontent.com/9551316/86617145-3644e480-bf8d-11ea-9a6b-645a99fccea5.png)

Unlike adwaita, the path dont have a box.  The path bar needs to fit in search button like:

![image](https://user-images.githubusercontent.com/9551316/86617367-7e640700-bf8d-11ea-98f3-de4a33deb6f7.png)

**Comment by sklei4** [comment]
The bar appears when you select the magnify glass, which is just as good. I prefer the current theme. I think Adwaita isn't the best design.

**Comment by isantop** [comment]
Fixed via #486
