### ISSUE TITLE
Support colorPrimary headerbar branding

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#47]
This is more of a discussion point than a for sure TODO. elementary, Granite, and AppCenter apps use the `@colorPrimary` GTK CSS variable to colorize the headerbar; you can see this in Eddy as well as apps like Football, Ciano, News, Notejot, Palaura, Swatches, and Vocal which all set the headerbar color with `@colorPrimary`.

Things to keep in mind:
- Supporting all three of our theme variants (standard, light, dark)
- Ensuring foreground (label and button colors) still contrast

This would be a nice step in the direction of better Granite/elementary API support, and would make apps designed originally for elementary OS fit in better on Pop!_OS.

**Comment by cassidyjames** [comment]
As a first run in the inspector, this would get us started:

```
headerbar {
    background-color: @colorPrimary;
}
```

...and then make sure we set a fallback in the theme to the current headerbar colors.

**Comment by isantop** [comment]
Since Pop is just a fairly opinionated theme wrt headerbars, this issue is going to be closed for now due to a lack of requisite design.
