### ISSUE TITLE
Not able to see the highlighted item in launcher when using light theme

### ISSUE THREAD

**Issue by sonulohani** [pop-os/gtk-theme#471]
**Describe the problem:**
While using light theme, when I use launcher and search something, in the search result couldn't able to see the highlighted part. The screenshot will give you more info about this.

![Screenshot from 2020-08-28 08-12-01](https://user-images.githubusercontent.com/2958681/91515426-c7d63000-e906-11ea-8f38-93e03f9dad24.png)

**Steps to reproduce:**
1. Open launcher using Super + / and type to search. Use light theme.

**Distribution:**

PRETTY_NAME="Pop!_OS 20.04 LTS"

**Pop version:**

Installed: 5.2.0~1593549084~20.04~8c31be9
error: org.gtk.Gtk3theme.Pop/*unspecified*/*unspecified* not installed

**Comment by jacobgkau** [comment]
I am not able to reproduce this issue on gtk-theme `8c31be9` (the same version) and pop-shell `8416328` (current stable):

![gtk-theme-i471-screenshot1](https://user-images.githubusercontent.com/7199422/91588982-38387d80-e916-11ea-80c7-ea091cb61df0.png)

**Comment by sonulohani** [comment]
Hi @jacobgkau 

Could you please switch appearance from light to dark and then to light and check. Thanks

**Comment by sonulohani** [comment]
Changing the shell to Pop in gnome-tweaks fixed this problem.

**Comment by kpuljek** [comment]
While this does solve the highlight problem, it's not a proper solution. 

If you change the shell-theme to Pop in gnome-tweaks, the shell theme no longer changes when you switch to Dark from the Appearance menu, leaving the shell Light. 

When I reset dconf settings for the User themes extension and switch back to the "Default" shell theme, it follows the Appearance menu, but the highlight bug is back.
