### ISSUE TITLE
20.10: Windows in overview overlap and touching each other

### ISSUE THREAD

**Issue by leviport** [pop-os/gtk-theme#474]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
I think it's a Gnome 3.38 thing

**Issue/Bug Description:**
When I enter the overview with more than one window open, window previews overlap or touch each other.

With tiling on: 
![scrunchy-overview](https://user-images.githubusercontent.com/13512097/95505289-58267c80-096b-11eb-85b0-7e0b4a5fb9a4.png)

Same windows, but with tiling off: 
![non-tiled-scrunch](https://user-images.githubusercontent.com/13512097/95505736-1944f680-096c-11eb-811d-dfe6f9f1b87e.png)

**Steps to reproduce (if you know):**
Open some windows and enter the overview

**Expected behavior:**
Windows should not overlap, and probably should space out a bit so the edges don't touch.

**Other Notes:**
"Show all applications" looks a little scrunched too, but nothing overlaps so it's probably okay:
![scrunched-apps](https://user-images.githubusercontent.com/13512097/95505826-3bd70f80-096c-11eb-995f-fd08d10d22a4.png)

**Comment by MaCroX95** [comment]
+1 for this bug.

> > I've heard reports that it doesn't happen on Adwaita.
> 
> I'm seeing the same thing after switching the theme to Adwaita:
> 
> ![Screenshot from 2020-10-09 11-22-44](https://user-images.githubusercontent.com/7199422/95613199-caf22f00-0a21-11eb-868d-ab248495af0e.png)

You have only switched the "Application" theme to Adwaita, shell theme is still pop's default theme. If you're trying out Adwaita log in into gnome-session instead of pop session.

Issue isn't present on Fedora with Adwaita or Ubuntu with Yaru shell theme, so I think it needs to be in the "shell theme component" of the Pop theme.

**Comment by isantop** [comment]
I believe I'm seeing this issue with the Adwaita, Yaru, and Pop themes selected (both Applications/GTK and Shell). This leads me to think that this is being caused by some patch we're applying to GNOME Shell, or possibly something related to Pop Shell.

**Comment by leviport** [comment]
I think it's unlikely to be related to pop-shell since pop-shell doesn't manipulate anything in the overview. I believe the only overview thing it does at all is detect when the overview opens so window management can be cancelled.

**Comment by isantop** [comment]
Yes, but I also doubt this is theme-related, since I'm seeing the issue with 3 different themes and the theme also doesn't affect window placement in the overview.

**Comment by jacobgkau** [comment]
Ah, this was my mistake earlier for not switching the shell theme. After installing the User Shell Themes extension and loading Adwaita using [these instructions](https://askubuntu.com/a/1231052), I am actually seeing the issue go away:

![Screenshot from 2020-10-12 16-10-15](https://user-images.githubusercontent.com/7199422/95794643-9d1d1c80-0ca5-11eb-9b26-65dcf710506c.png)

![Screenshot from 2020-10-12 16-10-46](https://user-images.githubusercontent.com/7199422/95794637-99899580-0ca5-11eb-9123-282800e51699.png)

Both the Adwaita and Pop application themes display properly if the shell theme is set to Adwaita; changing the shell theme back to Pop or Pop-dark brings the issue back.

**Comment by isantop** [comment]
I can't replicate this issue in Ubuntu 20.10 with the Pop Shell theme installed and selected either. I don't believe the shell theme is causing this.

**Comment by MaCroX95** [comment]
> Ah, this was my mistake earlier for not switching the shell theme. After installing the User Shell Themes extension and loading Adwaita using [these instructions](https://askubuntu.com/a/1231052), I am actually seeing the issue go away:
> 
> Both the Adwaita and Pop application themes display properly if the shell theme is set to Adwaita; changing the shell theme back to Pop or Pop-dark brings the issue back.

Thanks for confirming, same experience here :)

**Comment by ids1024** [comment]
Looking at the changes in https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/gnome-3-38/data/theme:

It looks like there aren't many changes to the theme, but [MR 1271](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1271) made substantial changes to how the app grid is handled, including changes to the theme. That's probably related.

**Comment by ids1024** [comment]
I guess if it's related to the Gnome Shell theme, it has to be one of these commits:

`git shortlog origin/gnome-3-36..origin/gnome-3-38 -- data/theme/`:

```
Björn Daase (1):
      *: Fix spelling mistakes found by codespell

Christopher Davis (1):
      CSS: Add border around avatars

Florian Müllner (4):
      screenshot: Add preview to color picker
      dateMenu: Add "Events" section
      style: Swap text-align in RTL locales
      polkitAgent: Drop separate user icon style

Georges Basile Stavracas Neto (6):
      search: Replace IconGrid from grid search results
      appDisplay: Remove Frequent view
      lookingGlass: Add actor tree inspector
      iconGrid: Use IconGridLayout
      theme: Adjust folder dialog CSS
      Add pagination to the folder dialog

Jakub Steiner (1):
      theme: tone down weekend with events

Jonas Dreßler (2):
      workspace: Remove WindowOverlay in favour of new overlays of WindowClone
      workspace: Use the new WorkspaceLayout for allocating window clones

Joonas Henriksson (1):
      calendar: Vertically center align week numbers

PrOF-kk (1):
      theme: Make world clock times tabular

Sebastian Keller (1):
      workspace: Use invisible guide actor to center overlay title on border
```

**Comment by ids1024** [comment]
> Ah, this was my mistake earlier for not switching the shell theme. After installing the User Shell Themes extension and loading Adwaita using these instructions, I am actually seeing the issue go away

I'm seeing the same behavior, now that I try Groovy.

I've tried updating the `.scss` files from the theme with the updates from upstream Gnome shell... but I haven't had any luck fixing this so far. Maintaining Gnome Shell themes seems like rather a pain...

**Comment by MaCroX95** [comment]
> > Ah, this was my mistake earlier for not switching the shell theme. After installing the User Shell Themes extension and loading Adwaita using these instructions, I am actually seeing the issue go away
> 
> I'm seeing the same behavior, now that I try Groovy.
> 
> I've tried updating the `.scss` files from the theme with the updates from upstream Gnome shell... but I haven't had any luck fixing this so far. Maintaining Gnome Shell themes seems like rather a pain...

Does it make sense to just rebase pop-theme on each upcoming adwaita release or is it less hassle leaving the old version and figuring out what changes broke something? Many distro developers are frustrated because adwaita doesn't really have a theming API, I'd suggest to most projects like Pop to change as little as possible and even that mostly in terms of color pallets and similar.

**Comment by TechnologyMan101** [comment]
Just to say, this issue does not occur on Fedora 33 Beta and Ubuntu 20.10 Beta.

**Comment by isantop** [comment]
> > > Ah, this was my mistake earlier for not switching the shell theme. After installing the User Shell Themes extension and loading Adwaita using these instructions, I am actually seeing the issue go away
> > 
> > 
> > I'm seeing the same behavior, now that I try Groovy.
> > I've tried updating the `.scss` files from the theme with the updates from upstream Gnome shell... but I haven't had any luck fixing this so far. Maintaining Gnome Shell themes seems like rather a pain...
> 
> Does it make sense to just rebase pop-theme on each upcoming adwaita release or is it less hassle leaving the old version and figuring out what changes broke something? Many distro developers are frustrated because adwaita doesn't really have a theming API, I'd suggest to most projects like Pop to change as little as possible and even that mostly in terms of color pallets and similar and rebase the theme every time that the upstream changes (so in major gnome version updates)

That's more or less how the theme is maintained and developed now. Most of the pop-level modifications are enabled in separate files.
