### ISSUE TITLE
Building from source doesn't respect modified Shell theme colors

### ISSUE THREAD

**Issue by AAnzel** [pop-os/gtk-theme#481]
**Describe the problem:**

**Steps to reproduce:**
1. Changing some colors in `gtk-theme/gnome-shell/src/gnome-shell-sass/_pop_os_colors.scss`, `gtk-theme/gnome-shell/src/gnome-shell-sass/_colors.scss`, etc.
2. Building according to [README.md](https://github.com/pop-os/gtk-theme/blob/master/README.md)
3. Modified GTK theme builds successfully, as seen below
![Screenshot from 2020-10-24 11-36-34](https://user-images.githubusercontent.com/44969003/97078572-50164000-15ed-11eb-8fee-4eb91bb33aaf.png)
However, Shell theme stays default, as seen below
![Screenshot from 2020-10-24 11-37-07](https://user-images.githubusercontent.com/44969003/97078575-51e00380-15ed-11eb-8d2e-f5a132140e65.png)

**Distribution:**

PRETTY_NAME="Pop!_OS 20.10"

**Pop version:**

    Installed: 5.3.0~1603307552~20.10~a5e0cc9
    error: org.gtk.Gtk3theme.Pop/*unspecified*/*unspecified* not installed

**Comment by isantop** [comment]
I can't replicate this issue on my end. After building and installing a modified copy of the theme from source and restarting the shell, the colors match the updated version that I made.
