### ISSUE TITLE
Filezilla: Bottom bar not styled 

### ISSUE THREAD

**Issue by kalenpw** [pop-os/gtk-theme#494]
**Describe the problem:**
The tabs in FileZilla do not match the rest of theme

![2020-12-15_21-04](https://user-images.githubusercontent.com/13550971/102303785-38867400-3f19-11eb-8e06-f2be4d28a7d0.png)

**Steps to reproduce:**
1. Notice the bottom bar with queued files and the middle bar with different connections

**Distribution:**
PRETTY_NAME="Pop!_OS 20.04 LTS"

**Pop version:**
Installed: 5.2.0~1599689740~20.04~11b9d22

**Comment by isantop** [comment]
FileZilla is a GTK2 app, and it appears to be using custom widgets for the widgets in question. They cannot be styled in the GTK Theme.
