### ISSUE TITLE
GNOME recipes elements look out of place.

### ISSUE THREAD

**Issue by VentGrey** [pop-os/gtk-theme#495]
The notes inside gnome-recipes look kinda odd when using the Pop! Theme. 
Using latest pop-theme from the repositories: `1.0.4~1571245319~20.10~ed52981`

![image](https://user-images.githubusercontent.com/24773698/103254002-3379e980-4949-11eb-8b78-7f51b61fc199.png)

GTKInspector shows this output text is a GtkLabel:
![image](https://user-images.githubusercontent.com/24773698/103254300-5eb10880-494a-11eb-879b-d8ac67dc53da.png)

**Comment by isantop** [comment]
Notes are being styled by the upstream application and cannot be overridden in the GTK theme, unfortunately.
