### ISSUE TITLE
PPA repository only for the theme

### ISSUE THREAD

**Issue by raffaem** [pop-os/gtk-theme#503]
I am trying to install Pop OS theme on Ubuntu 20.10

Is there a PPA repository for the theme only?

I am trying to use the one provided in README but it seems to be the repository for the entire Pop OS, and as such it is trying to update other system packages.

**Comment by bflanagin** [comment]
We're glad you find our theme appealing enough to install it without the rest of our ppa's updates. It should go without saying that we would prefer you follow the directions as stated in the README, but appreciate that it may not be for everyone. 

That being said we can only support those that install any of our packages through the companies suggested method. If you don't mind solving the issues you might have on your own you can directly download the debian files from the ppa directory here: http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-gtk-theme/

**Comment by raffaem** [comment]
> We're glad you find our theme appealing enough to install it without the rest of our ppa's updates. 

It's your merit, you did a very good job with this theme! How can't you love Pop OS theme? :)

I also installed the wallpapers!

> It should go without saying that we would prefer you follow the directions as stated in the README, but appreciate that it may not be for everyone.

The direction in your README says:
> Pop is intended to be installed through the package manager. Packages for Pop are available in PPA:

These instructions says to add the PPA and the install pop-theme afterwards.

```
sudo add-apt-repository ppa:system76/pop
sudo apt update
sudo apt install pop-theme
```

But if you do this at the next `apt-get upgrade` every other update from the PPA is grabbed.

The README of the PPA your README had me added [says](https://launchpad.net/~system76/+archive/ubuntu/pop):

> A repository for all Pop!_OS software components.
> 
> WARNING: This PPA is for Pop!_OS, **and it may cause breakage on other Ubuntu-based OS's**. Use of this repository on non-Pop_OS installations is at your own risk!

And I don't want my system to break.

> That being said we can only support those that install any of our packages through the companies suggested method. 

So you should support me because I have followed the company suggested method.

I have run the bash instructions in the README and installed the theme.

As the company suggested.

What I am saying is that now at the next `apt-get upgrade` all the other packages in the PPA repository would substitute the ones provided by Canonical.

Thank you for your support.

> If you don't mind solving the issues you might have on your own you can directly download the debian files from the ppa directory here: http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-gtk-theme/

I can also find other method to install the theme, like downloading from gnome-look or other repositories that contain it.

I just wanted to install the PPA to have the updates (of the theme) without breaking my system as the readme of the PPA you point to warns.

**Comment by jacobgkau** [comment]
> Is there a PPA repository for the theme only?

Answering this question more directly, no, there is not a PPA for the theme only. The theme is packaged for Pop!_OS. The source code is available for manual installation or re-packaging on other distributions.

Please read a bit farther down in the readme: https://github.com/pop-os/gtk-theme#installation-from-git-source

> ### Installation from Git Source
> ----------------------------
> This is the recommended method for users who aren't on Pop.

This would be the "suggested method" for vanilla Ubuntu.
