### ISSUE TITLE
Pop os themes interfere with other shell themes 

### ISSUE THREAD

**Issue by meliodas1107** [pop-os/gtk-theme#504]
pop themes come at other places (in shell and in some apps ) even when another theme (like yaru)is being used.
Please Note : I tried third party orchis theme as shell theme . And there was no issue. maybe it is for adwaita based theme issue . But there was no such problem with ubuntu when i tried adwaita shell theme .

![image](https://user-images.githubusercontent.com/57810820/109944317-20461a00-7cfc-11eb-9dce-fc17b92d35c2.png)
![image](https://user-images.githubusercontent.com/57810820/109944380-2dfb9f80-7cfc-11eb-85eb-ba5dc336e1c7.png)

**Steps to reproduce:**
1. Install yaru theme .
2. change shell theme to yaru .
3. open notification drawer . 
4. toggle Do not disturb button(it will have pop shell theme button instead of yaru ).

**Distribution:**

PRETTY_NAME="Pop!_OS 20.04 LTS"
**Pop version:**

apt: Installed: 5.2.0~1599689740~20.04~11b9d22
 flatpak :   Installed: 5.2.0~1599689740~20.04~11b9d22

**Comment by bflanagin** [comment]
For most themes you need to restart gnome for them to be fully applied. Usually you can get away with using the restart command in gnome:

`alt+f2` type `r` then press `enter`

If it still doesn't fully apply you may need to log out and log back in for it to take full affect.

**Comment by meliodas1107** [comment]
I think after reboot it solved . But It wasnt neded in other distros like fedora ubuntu ,etc.. 
Anyways I'm closing it then :) 
Thanks
