### ISSUE TITLE
Transparent rendering after VTE's 0.64.0 update

### ISSUE THREAD

**Issue by guihkx** [pop-os/gtk-theme#505]
**Describe the problem:**
Recently, the `vte3` package (Virtual Terminal library)  was updated on Arch Linux. That update introduced a bug in this theme where everything gets transparent on GNOME Terminal, like so:

![image](https://user-images.githubusercontent.com/626206/112476104-505b6880-8d50-11eb-8837-132a74e9990d.png)

This issue has been reported to the VTE folks about 6 months ago, but it was ruled out as a theme bug:

https://gitlab.gnome.org/GNOME/vte/-/issues/284

**Steps to reproduce:**
1. Update VTE to 0.64.0
2. Set the theme to Pop-dark
3. Open GNOME Terminal
4. Window contents are transparent

**Distribution:**
Arch Linux

**Pop version:**
5.3.1.r3.g5ab6f1e4-1 (from [this AUR package](https://aur.archlinux.org/packages/pop-gtk-theme-git/))

**Comment by jacobgkau** [comment]
In Pop!_OS, we don't set the terminal colors via the GTK theme; they're currently set via a gsettings override: https://github.com/pop-os/default-settings/blob/master_focal/debian/pop-default-settings.gsettings-override#L55 

The background on Pop, for either the light or the dark theme, is #333333:

![Screenshot from 2021-03-25 15-49-14](https://user-images.githubusercontent.com/7199422/112548772-5e29e180-8d82-11eb-9cf0-fe9aafe06097.png)

I see that in Arch, downgrading to VTE version 0.62.3-1 gets a legible terminal back, but the background color is #272727 in the dark theme and #ffffff in the light theme:

![arch-dark](https://user-images.githubusercontent.com/7199422/112548802-697d0d00-8d82-11eb-95bf-25bd0624d6b3.png)

![arch-light](https://user-images.githubusercontent.com/7199422/112548794-671ab300-8d82-11eb-9767-c983ae19cbae.png)

That's just the `base_color` variable in gtk-theme, which GNOME Terminal previously used as a fallback. We can fix the transparency fairly easily by defining `text_view_bg` to be the same as `base_color`. It still won't be the Pop color scheme, but it will be legible again.

**Comment by jacobgkau** [comment]
Using the 6% darkening for the background color in the dark theme that Adwaita uses, contrast does seem a bit better:

![term-2](https://user-images.githubusercontent.com/7199422/112550765-7fd89800-8d85-11eb-8959-62c96536bdae.png)

GNOME Contrast confirms the ratio with the new scheme is greater than the old one.

**Comment by guihkx** [comment]
Btw, I've tested the patch and now it works as expected:

![image](https://user-images.githubusercontent.com/626206/112698607-c9e67a00-8e68-11eb-9d75-b48a8431adec.png)

Thank you very much ❤️
