### ISSUE TITLE
[FEATURE REQUEST] Adjustable highlight colors to match pop-shell

### ISSUE THREAD

**Issue by jmbuhr** [pop-os/gtk-theme#508]
Since a couple of commits ago the pop-shell extension allows for the customization of the highlight color for the active window hint: https://github.com/pop-os/shell/search?q=active+hint

I would love a similar feature for the pop-gtk-theme to allow customization of the main highlight colors (orange and teal). This would allow users to feel even more at home, while still maintaining the overall look and feel of pop-os.

PS: I realize this is not an issue but more of a discussion point / feature request, but the mattermost link mentioned in the issue template appears to be no longer valid: https://chat.pop-os.org/ says `No teams are available to join. Please ask your administrator for an invite.`

**Comment by isantop** [comment]
The problem here is that the accent colors are baked into the CSS, and supporting customizable accent colors would require changes to both GTK and ST (for the Shell Theme) in order to change those programatically.

**Comment by jmbuhr** [comment]
Apologies for the duplicate issue, I completely overlooked  #490.
