### ISSUE TITLE
[openSUSE] Pop-up Authentification and Power Button menu size alignment bug

### ISSUE THREAD

**Issue by aldhiansyah** [pop-os/gtk-theme#524]
**Pop UP Authentification and Power Button menu size alignment bug :**

![Screenshot from 2021-07-08 15-43-05](https://user-images.githubusercontent.com/59528539/124893337-d69c7180-e004-11eb-90bc-707ed47a43fa.png)
and
![Screenshot from 2021-07-08 15-39-56](https://user-images.githubusercontent.com/59528539/124893578-0ea3b480-e005-11eb-812f-773afc51280d.png)

**Steps to reproduce:**
1. use Pop Dark and Pop Themes 
2. Click on power off menu in gnome panel 
**Distribution:**

NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"

GNOME  Version 3.34.7

**Comment by aldhiansyah** [comment]
run : cat /etc/os-release 

NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

**Comment by isantop** [comment]
The Pop Theme will generally require a version of GNOME newer than 3.34; 3.38 is the currently-recommended version.
