### ISSUE TITLE
Pop and Pop-Dark both give a dark shell theme

### ISSUE THREAD

**Issue by KarkanAlzwayed** [pop-os/gtk-theme#531]
**Describe the problem:**
Both Pop and Pop dark give the shell a dark theme (the panel drop down menu and right click on the desktop are both dark, for example)

**Steps to reproduce:**
Install through `git clone` on Fedora

**Distribution:**
Fedora 34 (Workstation Edition)

**Comment by isantop** [comment]
The shell theme is switched separately from the main GTK Theme and requires using the [User Themes](https://extensions.gnome.org/extension/19/user-themes/) extension.

**Comment by KarkanAlzwayed** [comment]
@isantop there isn't a "pop dark" choice for the shell in gnome tweaks, with the user themes installed and enabled.

**Comment by shalzz** [comment]
This is still an issue. With the User shell themes extension installed selecting "Pop" or "Pop-dark" does not make any difference. They both result in a dark shell theme.
Looking at the css they are essentially the same:

```
$ diff /usr/share/themes/Pop/gnome-shell/gnome-shell.css /usr/share/themes/Pop-dark/gnome-shell/gnome-shell.css
2213a2214,2243
> 
> /* Pop_OS COSMIC Widget styling. */
> /* Pop_OS COSMIC Dock styling, append !important to any changed rules */
> .cosmic-dock #dock {
>   border-radius: 12px 12px 12px 12px !important;
>   border: 1px solid rgba(255, 255, 255, 0.16);
>   background-color: #33302F;
>   margin: 4px !important; }
> 
> .cosmic-dock.extended #dock {
>   border-radius: 0px !important;
>   margin: 0 !important; }
> 
> .cosmic-dock.extended.side #dock {
>   border-top-width: 0 !important;
>   border-bottom-width: 0 !important; }
> 
> .cosmic-dock.extended.side.left #dock {
>   border-left-width: 0 !important; }
> 
> .cosmic-dock.extended.side.right #dock {
>   border-right-width: 0 !important; }
> 
> .cosmic-dock.extended.bottom #dock {
>   border-bottom-width: 0 !important;
>   border-left-width: 0 !important;
>   border-right-width: 0 !important; }
> 
> .cosmic-dock .app-well-app:hover .overview-icon, .cosmic-dock .app-well-app:focus .overview-icon, .cosmic-dock .app-well-app:selected .overview-icon {
>   border-radius: 11px; }
```

Tried on Arch with the official `pop-gtk-theme` pacakge
