### ISSUE TITLE
Missing elementary color palette from OS 6 Odin

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#541]
**Describe the problem:**

 It looks like the current Pop theme doesn't include the updated color palette variables from the elementary OS 6 Odin stylesheet. As a result, upstream versions of elementary apps like AppCenter and potentially installer and Sideload and third-party apps targeting elementary OS will look broken.

![Screenshot from 2021-09-16 11-43-11@2x](https://user-images.githubusercontent.com/611168/133659965-7e66b03b-d3f6-4f32-8fcd-3bb78aa285de.png)

![Screenshot from 2021-09-16 11-43-03@2x](https://user-images.githubusercontent.com/611168/133659989-155501f9-f4d6-4a34-b7f4-7c27c9208bb2.png)

**Steps to reproduce:**
1. Install AppCenter from upstream
2. See the missing colors

**Distribution:**

Tested on elementary OS 6 Odin

**Pop version:**

Pop theme from `master`

**Comment by cassidyjames** [comment]
Specifically, it looks like accent shades are missing, e.g.:

https://github.com/elementary/stylesheet/blob/983b83f6858a31af3bc2b7cd0f33a572dd8ec011/src/variants/orange.scss#L22-L29

**Comment by cassidyjames** [comment]
Ah, the specific issue with AppCenter is actually missing `text_color` and `accent_color`. It would be good to support the full accent palette but I'll get a minimal PR in to fix this specific case at least.

**Comment by isantop** [comment]
Closing as the relevant PR was merged successfully
