### ISSUE TITLE
flatpak Polari not working with flatpak Pop theme

### ISSUE THREAD

**Issue by Yuri6037** [pop-os/gtk-theme#549]
**Describe the problem:**
Today I got an update for Polari IRC client. I'm using the flatpak version and I noticed 3 issues:
- The app refused to load complaining that apparently my computer did not support OpenGL ES 2.0 (oryp7 not running GLES 2.0, lol?!). It turns out that the devs of Polari did not realize that hardware acceleration needs a flatpak permission (nice work GNOME). After forcing that permission by installing Flatseal (great UX for the end user by the way, install an app which will fail to run silently because you did not allow hardware acceleration, will tell GNOME about that).
- The system theme, which is the default Pop OS theme light variant, wasn't applied to Polari anymore. I suspect GNOME runtime 41 is not accepting Pop theme anymore...
- The computer is running hotter (it turns out Polari decided it was good for a stupid IRC client to run one CPU core full).

I report this here only for the theme problem, I will report the 2 other problems to GNOME Polari directly.

**Steps to reproduce:**
1. Install flatpak version of Polari

**Distribution:**
Pop!_OS 21.04

**Pop version:**
- `runtime/org.gtk.Gtk3theme.Pop/x86_64/3.22 (commit 1eac06f6a58047fd6717a13f12b744ea59e6f9829fed02d856a5efb998b318a5)`
- `5.3.3~1625837590~21.04~11bcd41`

**Comment by isantop** [comment]
This is due to limitations with LibAdwaita, which prevents loading the system theme. The issue should be filed against LibAdwaita, here: https://gitlab.gnome.org/GNOME/libadwaita/-/issues

**Comment by Yuri6037** [comment]
Thank you but I've just filled that issue on libadwait who told me that this is intended behavior. Is there any way you provide a patched version of libadwaita which fixes this bug on Pop OS? It's really annoying to see apps using totally different theming on this OS.

**Comment by BrainBlasted** [comment]
Please do not redirect issues to libadwaita for that. The stylesheet handling is intentional :)

**Comment by Yuri6037** [comment]
Apparently this is not libadwaita problem: 

Quote from https://gitlab.gnome.org/GNOME/libadwaita/-/issues/277:
"Also, Polari isn't currently using libadwaita. Your issue is likely due to there being no GTK4 extension for the Pop theme on Flathub."

Do you confirm no extension for Gtk4 are available on the flathub?

**Comment by isantop** [comment]
> Please do not redirect issues to libadwaita for that. The stylesheet handling is intentional :)

Intentional or not, if a user of my software projects is experiencing an issue that is beyond my capability to fix, I am entitled to direct them to the appropriate place to report said issue.

> Do you confirm no extension for Gtk4 are available on the flathub?

If Polari isn't currently using LibAdwaita, then that is correct. GTK4 extensions to the theme are expected to be released next month.

**Comment by BrainBlasted** [comment]
> EDIT: Also according to them, as a distribution provider you should be providing your own lib to fix this problem.

That's a misinterpretation of my statement. What I meant was different desktop environments that want to ship GTK (not GNOME) apps can work together and create one with theming support as they see fit. I did not mean that distros should be replacing/patching libadwaita for GNOME apps.

> Intentional or not, if a user of my software projects is experiencing an issue that is beyond my capability to fix, I am entitled to direct them to the appropriate place to report said issue.

I understand that, but in this case it's not an issue upstream, and thus not appropriate for us. In the future, you could perhaps say that changing the stylesheet is not supported for GNOME applications and that it's intended behavior.

**Comment by jackpot51** [comment]
@isantop please update the flatpak theme to support GTK4 when you can.

**Comment by jackpot51** [comment]
It looks like work was already started but not finished: https://github.com/flathub/org.gtk.Gtk3theme.Pop/pull/7

**Comment by jackpot51** [comment]
Closed, since this has nothing to do with Polari, and opened a new more specific issue: https://github.com/pop-os/gtk-theme/issues/553

**Comment by isantop** [comment]
Yep, was looking at several things wrt to that. It's good to know that Polari _should_ support the theme correctly, as every other app I tested using Gtk4 was also using Libadwaita

**Comment by jackpot51** [comment]
For the future instances of bugs like this from applications that actually do use libadwaita, just close and wontfix. Do not direct them to open an issue on libadwaita or the application itself.
