### ISSUE TITLE
Calendar text unreadble when using dark theme on 21.04

### ISSUE THREAD

**Issue by richardzhou666** [pop-os/gtk-theme#552]
**Describe the problem:**

![image](https://user-images.githubusercontent.com/62457582/134737792-cf9be43e-11ba-4cc0-a917-6238be81bd57.png)
![image](https://user-images.githubusercontent.com/62457582/134737812-bf00ad80-c226-4c88-bae6-d24ed4ca6e68.png)
What it should look like when using light theme
![image](https://user-images.githubusercontent.com/62457582/134738000-59197241-dc97-4db0-86a4-1f40b5a3ce04.png)

**Steps to reproduce:**
1. Open calendar when using dark theme

**Distribution:**
Pop!_OS 21.04

**Pop version:**
Installed: 5.3.3~1625837590~21.04~11bcd41

**Comment by jacobgkau** [comment]
Hmm, I'm not seeing this with GNOME Calendar and the dark theme on 21.04 on my own machine:

![Screenshot from 2021-09-24 15-24-21](https://user-images.githubusercontent.com/7199422/134741262-b1af615e-5600-4994-a092-05a9fe5a8c18.png)

The close button also has a white circle inside of it in the OP's screenshots, which shouldn't be there AFAIK.

**Comment by jackpot51** [comment]
I'm also not seeing this. @richardzhou666 are you sure you have the Pop theme installed?

**Comment by jackpot51** [comment]
The minimize, maximize buttons are weird too.

**Comment by richardzhou666** [comment]
I just checked the Themes settings in Tweaks and realized I am not using Pop Icons. After changing it to Pop, it is working fine now.
