### ISSUE TITLE
CSS issue causing logs to fill up in some cases

### ISSUE THREAD

**Issue by nathandyer** [pop-os/gtk-theme#563]
**Describe the problem:**
 
Hello! I have received reports from some customers that their logs are filling up with thousands of lines, such as these:
 
```
Dec 16 17:18:14 laptop hidpi-daemon[3099]: Theme parsing error: gtk.css:1:62: Failed to import: The resource at
/org/pop-os/themes/Pop/3.20/gtk.css
Dec 16 17:18:14 laptop gsd-xsettings[3114]: Theme parsing error: gtk.css:1:62: Failed to import: The resource at
/org/pop-os/themes/Pop/3.20/gtk.css
Dec 16 17:18:14 laptop gsd-media-keys[3096]: Theme parsing error: gtk.css:1:62: Failed to import: The resource at
/org/pop-os/themes/Pop/3.20/gtk.css
Dec 16 17:18:14 laptop gsd-power[3098]: Theme parsing error: gtk.css:1:62: Failed to import: The resource at
/org/pop-os/themes/Pop/3.20/gtk.css
Dec 16 17:18:14 laptop gsd-wacom[3113]: Theme parsing error: gtk.css:1:62: Failed to import: The resource at
/org/pop-os/themes/Pop/3.20/gtk.css
Dec 16 17:18:14 laptop gsd-color[3089]: Theme parsing error: gtk.css:1:62: Failed to import: The resource at
/org/pop-os/themes/Pop/3.20/gtk.css
```
 
After tracking this down, it appears to be related to:
 
`Theme parsing error: gtk.css:5000:25-30: Junk at end of value for background.`
 
which seems to correspond to:
 
/usr/share/themes/Pop/gtk-3.0/gtk.gresource
 
lines:
 
```
10156: background: alpha(black, 0.2); }
20946: background: alpha(black, 0.2); }
```
 
 
**Steps to reproduce:**
 
* Seems to happen automatically on the affected systems, but opening the GNOME extensions app was found to be a sure-fire way to trigger the output in the logs
 
**Distribution:**
Pop!_OS 21.10
 
 
**Pop version:**
* Installed: 5.4.5~1634918910~21.10~23d7ac8
* Pop Gtk theme - Pop Gtk theme used by System76

ID: org.gtk.Gtk3theme.Pop
Ref: runtime/org.gtk.Gtk3theme.Pop/x86_64/3.22
Arch: x86_64
Branch: 3.22
Origin: flathub
Collection: org.flathub.Stable
Installation: user
Installed: 1.1 MB

Commit: 1eac06f6a58047fd6717a13f12b744ea59e6f9829fed02d…
Parent: bf0014cc176fe2a66eb69045bc3ed80663e09240dda1db9…
Subject: add flathub.json (84e0033a)
Date: 2020-11-17 21:00:45 +0000

**Comment by isantop** [comment]
I believe this issue should now be fixed (As of #566 )

Please reopen if that's not the case.
