### ISSUE TITLE
App launcher text is dark when it should be light

### ISSUE THREAD

**Issue by jcs224** [pop-os/gtk-theme#565]
**Describe the problem:**

I started having this issue with Pop 21.04, still with 21.10. The app launcher (the menu you bring up when hitting the super key) is showing dark text on the highlighted item when it should be showing light text. I've tried finding something in GNOME Tweaks but to no avail. Any ideas?
I'm not sure what caused it, I have never messed with the theme. Except maybe to change it from light to dark and back, and this isn't a problem in non-dark mode. It is an issue in the other dark modes (adwaita-dark, HighContrast, etc.)

![image](https://user-images.githubusercontent.com/6226188/147900993-7daacf71-d828-49e0-9af6-395e9a167565.png)

**Steps to reproduce:**
1. Hitting the Super key while in a dark theme

**Distribution:**

Pop!_OS 21.10

**Pop version:**

5.4.5~1634918910~21.10~23d7ac8

```
Pop Gtk theme - Pop Gtk theme used by System76

          ID: org.gtk.Gtk3theme.Pop
         Ref: runtime/org.gtk.Gtk3theme.Pop/x86_64/3.22
        Arch: x86_64
      Branch: 3.22
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 1.1 MB

      Commit: 1eac06f6a58047fd6717a13f12b744ea59e6f9829fed02d856a5efb998b318a5
      Parent: bf0014cc176fe2a66eb69045bc3ed80663e09240dda1db97b5394ba3a501bea3
     Subject: add flathub.json (84e0033a)
        Date: 2020-11-17 21:00:45 +0000
```

**Comment by aliceTheGrinseCatz** [comment]
Yeah, this was actually a problem of the beta but I got it again since a updated my clean installed Pop!_OS 21.10...

**Comment by pbui** [comment]
This appears to happen if you use `Pop` for the `Application` theme and `Pop-dark` for the `Shell` theme.  Only use `Pop` or `Pop-dark` for both the `Application` and `Shell` theme does not appear to have this issue... So basically, users cannot mix light and dark `Application` and `Shell` themes.

**Comment by michaelaye** [comment]
but where are those choices? All I see is this in my settings:
![image](https://user-images.githubusercontent.com/69774/148297802-49bd045f-a32b-4ff6-b06a-e7829669c124.png)

**Comment by pbui** [comment]
> but where are those choices? All I see is this in my settings: ![image](https://user-images.githubusercontent.com/69774/148297802-49bd045f-a32b-4ff6-b06a-e7829669c124.png)

As discussed on Mattermost, you can access the individual `Applications` and `Shell` themes in `gnome-tweaks`.

Likewise, as discussed in chat... it appears that setting these global Light and Dark values only updates the Gtk theme and not necessarily the gnome-shell theme.  This can lead to cases where users end up with mixed light and dark themes if they had configured things separately with `gnome-tweaks`.

PS. @michaelaye was able to resolve this by using `gnome-tweaks` to only use either `Pop` or `Pop-dark` for the `Applications` and `Shell` themes.

**Comment by jcs224** [comment]
@pbui Thanks, that fixed it for me! Still not sure why it stopped working randomly though.

I had to go through this article to resolve the issue, since I got the error `Shell user-theme extension not enabled`:
https://ubuntuhandbook.org/index.php/2017/05/enable-shell-theme-in-gnome-tweak-tool-in-ubuntu/

**Comment by aliceTheGrinseCatz** [comment]
> This appears to happen if you use `Pop` for the `Application` theme and `Pop-dark` for the `Shell` theme. Only use `Pop` or `Pop-dark` for both the `Application` and `Shell` theme does not appear to have this issue... So basically, users cannot mix light and dark `Application` and `Shell` themes.

Nope, it's happen on two of four laptops, I care about, even if the User Themes is deactivated (what it was by default). I solve this issue now by activating User Themes and set the shell theme from default to "Pop dark"…
