### ISSUE TITLE
Disabling Cosmic Workspaces turns top bar black

### ISSUE THREAD

**Issue by Crylia** [pop-os/gtk-theme#568]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**
Upgrade
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Cosmic Workspaces V6

**Issue/Bug Description:**
Turning this extension off causes the top bar to turn black

**Steps to reproduce (if you know):**
Turn off the extension

**Expected behavior:**
top bar to remain the theme color

**Comment by isantop** [comment]
I can't seem to reproduce this issue currently.

**Comment by jacobgkau** [comment]
This was fixed by https://github.com/pop-os/gtk-theme/pull/567 and https://github.com/pop-os/cosmic-workspaces/pull/34, which moved the top bar color from the COSMIC Workspaces extension to the Pop shell theme.
