### ISSUE TITLE
[22.04] GNOME 42 OSDs are not themed properly

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/gtk-theme#573]
**Describe the problem:** After updating a Pop!_OS 22.04 pre-release system to GNOME 42, the OSDs for volume adjustment, touchpad enable/disable, etc. are themed poorly. They now show up near the bottom of the screen, and partially overlap with the dock (even if we wanted them to be lower on the screen to match GNOME, we should probably at least raise them above the dock's default position.)

![Screenshot from 2022-03-17 13-58-14](https://user-images.githubusercontent.com/7199422/158885538-31490401-82e8-464e-a99e-d55a2709a912.png)

(The volume OSD looks slightly different when [using pipewire](https://github.com/pop-os/desktop/pull/80), so it's probably best to have that installed when working on this.)

![Screenshot from 2022-03-17 14-01-49](https://user-images.githubusercontent.com/7199422/158885990-0618bc95-153f-4893-a24e-8153e991c4fb.png)

For the touchpad enable/disable OSD, the icon is not centered within the overlay:

![Screenshot from 2022-03-17 13-58-27](https://user-images.githubusercontent.com/7199422/158886035-ffb7898b-d1bd-4756-89fc-910ac4fdb004.png)

This also affects a new OSD for `PrtSc` (that key used to just take a screenshot without showing an OSD):

![Screenshot from 2022-03-17 13-59-01](https://user-images.githubusercontent.com/7199422/158886041-2f90113a-e351-4ba0-bde8-51a35f277498.png)

**Steps to reproduce:**
1. Install 22.04
2. Add master staging branch
3. Upgrade to GNOME 42

**Distribution:** Pop!_OS 22.04 LTS

**Pop version:** `5.4.5~1645564624~22.04~d3e2898`

**Comment by yusi1** [comment]
Same issue with me

**Comment by isantop** [comment]
I believe this is fixed as of 1dee9f5e2da405569dc8a714d6af563bfe213b5f
