### ISSUE TITLE
The Calendar in the Overview Does Not Indicate Events With Dots in Light Mode

### ISSUE THREAD

**Issue by Banjalucan** [pop-os/gtk-theme#582]
**Describe the problem:**

The Calendar in the overview does not indicate events with dots in light mode. Dark mode works fine. 
![image](https://user-images.githubusercontent.com/7347213/169683340-86f357c8-4bcd-434c-a899-90829a60b3f9.png)

**Steps to reproduce:**
1. Switch to light mode. 

**Distribution:**

**Pop version:**

apt policy pop-gtk-theme | grep -i installed:
`5.5.1~1651080726~22.04~1509852`

flatpak info org.gtk.Gtk3theme.Pop:
```
Pop Gtk theme - Pop Gtk theme used by System76

ID: org.gtk.Gtk3theme.Pop
Ref: runtime/org.gtk.Gtk3theme.Pop/x86_64/3.22
Arch: x86_64
Branch: 3.22
Origin: flathub
Collection: org.flathub.Stable
Installation: user
Installed: 1,1 MB

Commit: 1eac06f6a58047fd6717a13f12b744ea59e6f9829fed02d856a5efb998b318a5
Parent: bf0014cc176fe2a66eb69045bc3ed80663e09240dda1db97b5394ba3a501bea3
Subject: add flathub.json (84e0033a)
Date: 2020-11-17 21:00:45 +0000
```

**Comment by n3m0-22** [comment]
I can confirm this.
