### ISSUE TITLE
GTK 4 apps and system apps like Settings are not themed

### ISSUE THREAD

**Issue by MindlessDreams** [pop-os/gtk-theme#585]
**Describe the problem:**
Hello, thanks for the beautiful theme. I added it to my system by extracting the theme files from running PopOS 22.04. It runs great with one major issue for me - the theme is not applied to the gtk-4 applications ( like Settings for example). I tried moving the files from /gtk-4 folder of the theme to ~/.config/gtk-4.0 but it does not seem to have effect. Please advise how to apply the theme to the gtk-4 apps as well. Thank you!
![settings](https://user-images.githubusercontent.com/103588255/174467410-51e678d6-90e5-4991-86b6-e72419323067.png)

**Steps to reproduce:**
Manually install the theme to gnome 42 system.

**Distribution:**

PRETTY_NAME="Fedora Linux 36.20220617.0 (Silverblue)"

**Pop version:**

    Pop Gtk theme - Pop Gtk theme used by System76

          ID: org.gtk.Gtk3theme.Pop
         Ref: runtime/org.gtk.Gtk3theme.Pop/x86_64/3.22
        Arch: x86_64
      Branch: 3.22
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1.1 MB

      Commit: 1eac06f6a58047fd6717a13f12b744ea59e6f9829fed02d856a5efb998b318a5
      Parent: bf0014cc176fe2a66eb69045bc3ed80663e09240dda1db97b5394ba3a501bea3
     Subject: add flathub.json (84e0033a)
        Date: 2020-11-17 21:00:45 +0000

**Comment by isantop** [comment]
LibAdwaita and GNOME 42 have disabled theming, and such applications cannot be themed. Sorry about the inconvenience.

**Comment by MindlessDreams** [comment]
Thank you for your answer. Yet in PopOS 22.04 the settings are in the theme corresponding colours. How is this achieved and how do I replicate it on my system?
