### ISSUE TITLE
Fedora 36 - Light shell theme incorrectly dark when built from source & dark shell theme not found

### ISSUE THREAD

**Issue by seanleavy** [pop-os/gtk-theme#588]
When the project is built from the source master branch, the pop gnome-shell light theme variant is dark & no pop gnome-shell shell dark theme option is available. 

**System**:
Fedora 36
Gnome Shell 42.2

**Build commands used**:

```
meson build && cd build
ninja
ninja install
```

**Pop dark shell theme not found**

![Screenshot from 2022-07-08 13-20-20](https://user-images.githubusercontent.com/2906363/177991138-9ed19884-866d-4a80-bfb0-262c1088e029.png)

**Pop theme folder contents:**

![Screenshot from 2022-07-08 13-20-35](https://user-images.githubusercontent.com/2906363/177991235-60d26054-fc07-40cc-9873-f55d9a128daa.png)

**Pop dark theme folder contents:**

![Screenshot from 2022-07-08 13-20-41](https://user-images.githubusercontent.com/2906363/177991275-102348f9-aadc-40a2-9ae7-9799d084e61c.png)

**Pop light shell theme is actually dark:**

![Screenshot from 2022-07-08 13-25-18](https://user-images.githubusercontent.com/2906363/177991763-4b06e546-26f5-42d5-9fa3-ba9f80313dca.png)

ninja install logs:
[logs.log](https://github.com/pop-os/gtk-theme/files/9074869/logs.log)

**Comment by isantop** [comment]
You'll need to modify the `meson_options.txt` file and change the `gnome-shell-gresource` item to `true`
