### ISSUE TITLE
A few bugs on dark-theme

### ISSUE THREAD

**Issue by rtheodoro** [pop-os/gtk-theme#599]
The dark theme doesn't looks like it should be. Can I re-install it?

It's hard to read the texts. In my other PC its differente,.

![Captura de tela de 2022-12-21 00-10-06](https://user-images.githubusercontent.com/36709613/208812186-c68e13e0-31ce-44b3-ad8e-6d5622cb99ad.png)
![Captura de tela de 2022-12-21 00-09-37](https://user-images.githubusercontent.com/36709613/208812189-af5d45ab-7acb-4e55-9dfc-bca1c85d1c66.png)

I did try:

```bas

sudo apt reinstall pop-gtk-theme

```

Alt + F2

r

But it didn´t solve

**Describe the problem:**
The dark theme doesn't looks like it should be

**Steps to reproduce:**
Just open the applications or hit super

**Distribution:**
PRETTY_NAME="Pop!_OS 22.04 LTS"

**Pop version:**

apt policy pop-gtk-theme 
pop-gtk-theme:
  Instalado: 5.5.1~1664464633~22.04~e09de35
  Candidato: 5.5.1~1664464633~22.04~e09de35
  Tabela de versão:
 *** 5.5.1~1664464633~22.04~e09de35 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
     5.2.0~1586289568~20.04~f35b83b~ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy/universe i386 Packages

flatpak info org.gtk.Gtk3theme.Pop
erro: org.gtk.Gtk3theme.Pop/*unspecified*/*unspecified* não instalado

**Comment by leviport** [comment]
I think there's something wrong with the way your theme is configured. This is what the defaults should look like:

![Screenshot from 2022-12-21 07-25-49](https://user-images.githubusercontent.com/13512097/208928203-eb5eb74f-afc5-4804-ab26-e6377c9dc0fd.png)
![Screenshot from 2022-12-21 07-26-26](https://user-images.githubusercontent.com/13512097/208928213-54e00a5e-b245-420c-a633-66742768c5e5.png)

**Comment by rtheodoro** [comment]
Yep! Maybe something went wrong during my installation.

**Comment by isantop** [comment]
I'm going to go ahead and close this issue for now. Please feel free to reopen it if you continue to experience problems!

**Comment by rtheodoro** [comment]
Thanks, I just did a full re-install Pop  and now its everything ok.
