### ISSUE TITLE
No notification sound!

### ISSUE THREAD

**Issue by cesarrew** [pop-os/gtk-theme#601]
**Describe the problem:**

I'm not getting any notification sound when receiving a new chat message alert from Teams (web app) for example. I've confirmed that the property /org/gnome/desktop/sound/event-sounds is set to "true" and tried to use the tool notify-send to test if I would get a sound and the same problem happens. No sound at all.

 

![no_sound](https://user-images.githubusercontent.com/17600341/216402976-738f32ea-3432-4587-8e45-859a3d8996ab.png)

**Steps to reproduce:**
1.  Using the notify-send tool, send a notification using the command bellow for example:
notify-send "A new notification..."

**Distribution:**
Pop!_OS 22.04 LTS

**Pop version:**
pop-gtk-theme: 5.5.1~1664464633~22.04~e09de35

**Comment by isantop** [comment]
GNOME Shell does not play a sound when displaying a notification; notification sounds are currently the responsibility of the application. There may be a setting in Teams to play a notification sound though.
