### ISSUE TITLE
Boxes formed and background blurred abnormally in lock screen.

### ISSUE THREAD

**Issue by dexprexxtion** [pop-os/gtk-theme#602]
**Describe the problem:**
In the lock screen, black boxes with medium opacity are formed around the password input box, the user picture, the top bar, etc.
The boxes appear and change position every second, often forming a pattern.
(1) Sometimes the boxes appear and the background image of the desktop is blurred normally but the boxes remain.
(2)However, sometimes the entire background becomes black and the desktop wallpaper is visible only in the areas of the boxes, blurred.

When tried to take a screenshot, it could only be taken of (2) which is included below along with my desktop wallpaper to better understand the issue.

![Lock screen](https://user-images.githubusercontent.com/114414974/222945076-6203031c-c70c-41d7-9cd4-d37bda7d6ff8.png)
Lock screen
![Wallpaper](https://user-images.githubusercontent.com/114414974/222945091-1375e3ab-b49d-4b64-af7d-dfef4ecb900a.jpg)
Wallpaper

**Steps to reproduce:**
I don't really think this can be reproduced but I'll still provide some details.
1. Set the wallpaper provided or any wallpaper.
2. Go to the lock screen.
3. Scroll to get the password input dialog.

And the boxes appear.

**Distribution:**
Pop!_OS 22.04 LTS

**Pop version:**
Installed: 5.5.1~1664464633~22.04~e09de35
`flatpak info org.gtk.Gtk3theme.Pop` returns `error: org.gtk.Gtk3theme.Pop/*unspecified*/*unspecified* not installed` even though I clearly use the pop_dark theme as shown below.
![Screenshot from 2023-03-05 11-58-53](https://user-images.githubusercontent.com/114414974/222945418-e8cf367f-ffcf-475c-b400-ad7062709873.png)

    
**Specifications**
CPU: Intel® Core™ i5-2400 CPU @ 3.10GHz × 4 
RAM: 8.0 GiB
Graphics: NV96
Disk Capacity: 240.1 GB SSD
GNOME version: 42.5
Windowing System: X11

**Comment by leviport** [comment]
> Graphics: NV96

My guess is that this is a quirk with the Nouveau driver. At least, I'm assuming that you aren't running a super old Nvidia driver that supports that card?
