### ISSUE TITLE
Issue on navigation bar of Files application, appears wrong rectangle at the beginning of the navigation bar

### ISSUE THREAD

**Issue by martinonicolas** [pop-os/gtk-theme#603]
**Describe the problem:**
When the path of the current folder is too large for the size of the window, appears wrong rectangle at the beginning of the navigation bar.
-  *Minimal windows width size (with error)* Could it be the icon?
![2023-05-26_09-58](https://github.com/pop-os/gtk-theme/assets/28790864/8c06a10d-cfd8-43ae-a505-f86355e1401e)

- *Medium width size (is ok)*
![2023-05-26_09-59 semi ](https://github.com/pop-os/gtk-theme/assets/28790864/b263af60-07b5-419d-9d8d-7c59f4235790)

- *Large width size*
![2023-05-26_10-00 large ](https://github.com/pop-os/gtk-theme/assets/28790864/222647e7-5eaa-463f-942b-1fefe97c507a)

**Steps to reproduce:**
1. Open Files Application 
2. Navigate deep into the folders of your system
3. Resize de window to the minumum size allowed

**Distribution:**
Pop!_OS 22.04 LTS

**Pop version:**
```bash
sudo apt search pop-gtk-theme
Ordenando... Hecho
Buscar en todo el texto... Hecho
pop-gtk-theme/jammy,jammy,now 5.5.1~1664464633~22.04~e09de35 all [instalado, automático]
  Pop GTK Theme
```
```bash
flatpak info org.gtk.Gtk3theme.Pop
error: org.gtk.Gtk3theme.Pop/*unspecified*/*unspecified* no instalado
```

**Comment by leviport** [comment]
I'm seeing this as well. Good find!

![Screenshot from 2023-05-26 08-28-52](https://github.com/pop-os/gtk-theme/assets/13512097/a736e618-7372-4c3c-a102-8065d8797cb0)

**Comment by halfmexican** [comment]
so glad this got fixed
