### ISSUE TITLE
Actually install the plank theme

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#67]
We added a plank theme, but it's not being installed.

**Comment by cassidyjames** [comment]
Looks like it got removed when we synced from upstream: https://github.com/system76/pop-gtk-theme/commit/38fee1e42fc4892e4925acb86513ae01b7da02db#diff-3fbb47e318cd8802bd325e7da9aaabe8L120

**Comment by cassidyjames** [comment]
Fixed in #106

**Comment by cassidyjames** [comment]
I guess these stay open until `version-3` is released

**Comment by isantop** [comment]
Closed since Version-3 is released.
