### ISSUE TITLE
Backdrop styles

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#72]
There are a number of things we could do (which other themes do) to improve the distinction between focused and unfocused (backdrop) windows.

- Update toolbar colors to match titlebars
- Desaturate colored UI elements like switches
- Lower contrast of foreground elements like labels
- Reduce shadows

Adwaita and elementary are good examples to take some inspiration from. They both reduce depth of shadows/gradients and more significantly decrease contrast.

**Comment by isantop** [comment]
Will be working on this for the 3.0 version

**Comment by isantop** [comment]
Current progress is in version-3 93c4b5b8e6231ff0d3afc0ff91f31ff1b7e8bade
