### ISSUE TITLE
Can we have a variant which uses less vertical space?

### ISSUE THREAD

**Issue by berenddeboer** [pop-os/gtk-theme#84]
I would like to have a theme with less vertical space, i.e. tabs, menu less vertical height, and border with greatly reduced title bar. Gives me more vertical space.

Otherwise, looks gorgeous!

**Comment by isantop** [comment]
Thanks for your comment! We already ship the -slim/-compact variants which reduce the padding and spaces used by most widgets. You'll probably want to have a look at this.
