### ISSUE TITLE
Window buttons on Terminal

### ISSUE THREAD

**Issue by adithyaharun** [pop-os/gtk-theme#85]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - Ubuntu 17.10
 * Gtk+ 3.0 version - 3.22.25-0ubuntu0.1
 * Desktop environment - GNOME
 * Pop version - 2.2.3r0
 ```

**Related Application and/or Shell theming (or name of widget)**
Related Application: Terminal

**Actual issue**
The window buttons in the Terminal on the top-right corner is shown like the image below. I've tried to restart GNOME shell and restarting the computer, but still not worked.

![screenshot from 2017-11-19 18-43-34](https://user-images.githubusercontent.com/7106825/32989883-c9a154bc-cd59-11e7-8924-84b8559e9c46.png)

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
This issue has something to do with upstream implementations of non-CSD titlebars. It's partially related to the icon theme. I can't seem to reproduce it in the `version-3` branch, so I'm thinking this may be going away with the new update soon.

**Comment by adithyaharun** [comment]
Thank you very much.

Additional info: I found that this problem is not occurred when I logged in to the default Ubuntu (not X.org).
