### ISSUE TITLE
Warning text has low contrast in Shell dialogs

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#87]
Yellow warning text on a white background, doesn't appear to be WCAG AA or AAA compliant. We should use a darker shade if possible.

![screenshot from 2017-11-20 10-16-44](https://user-images.githubusercontent.com/611168/33031807-918db678-cddc-11e7-8a06-11bae18d47aa.png)

**Comment by isantop** [comment]
So, it appears this uses the same style classes as the same text on the login screen (which uses a dark background). We'll need to find a shade that is as visible as possible on both the light background as well as the dark one.
