### ISSUE TITLE
Way too big Top Bar

### ISSUE THREAD

**Issue by cybbro** [pop-os/gtk-theme#88]
I don't know whether it's a bug or not, but top bar is way too big, I found how to remove round corners but could you please tell me which line defines the size of the top bar so I could make it smaller? 

Thank you.

![Image](https://www.imageupload.co.uk/images/2017/11/25/Screenshotfrom2017-11-2512-30-51.png)

**Comment by isantop** [comment]
The Panel has min-height and max-height properties defined in src/gnome-shell/3.26/sass/widgets/_topbar.scss

However, you might look at using the -slim version of the them from the `version-3` branch, as it will have a much smaller top bar.
