### ISSUE TITLE
Windows don't animate into "Activities"

### ISSUE THREAD

**Issue by Raytar** [pop-os/gtk-theme#93]
**Reporter info**

```
 * Distribution - Fedora 27
 * Gtk+ 3.0 version - 3.22.26
 * Desktop environment - GNOME 3.26
 * Pop version - 3.0.0-b1
 ```

**Actual issue**

The window "spread" transition animation only works when exiting Activities.

**Steps to reproduce**

Open Activities.

**Expected behavior**

The windows should transition both in and out.

**Behavior in Adwaita**

As expected.

[Video showing first Pop and then Adwaita](https://imgur.com/HjWGoOs)

**Comment by isantop** [comment]
Only happens on the primary monitor.

**Comment by jlemonde** [comment]
I have the same problem. This is getting very annoying ! Hopefully a fix is going to be released soon !
PS : I have an interesting fact : when you use Dash to Panel (which I don't, but I tried), the transition works both in and out.

**Comment by kpuljek** [comment]
I figured this was by design, but if it's a bug I'd prefer it to be animated.

**Comment by isantop** [comment]
It's definitely due to a bug, but I can't figure out where the property is being specified. The Pop GNOME Shell theme is based (eventually) on the Adwaita theme codebase. It's just broken out into separate files to be more readable.

**Comment by kpuljek** [comment]
Spent an our digging and comparing the pop and adwaita .css files and I can't find the line that defines the animation length

**Comment by isantop** [comment]
Found it, there's an errant overview styling that's been breaking it.

**Comment by nana-4** [comment]
also please check the my comment at https://github.com/nana-4/materia-theme/pull/197#issuecomment-358268724

**Comment by isantop** [comment]
@nana-4 Putting the &:overview back into the and setting the border to transparent does not fix this issue.

**Comment by kpuljek** [comment]
Changing this one line in gnome-shell.css solved the issue for me. That's the only change I made, so @nana-4 is right, it just needs to be properly added to the source code.

![screenshot from 2018-01-19 18-07-34](https://user-images.githubusercontent.com/9851336/35162455-b9383054-fd43-11e7-854f-fd86a113ef06.png)

**Comment by nana-4** [comment]
@isantop I guess you are applying Pop specific `gnome-shell-theme.gresource` to your system and didn't apply that change to the `gresource`. `gnome-shell.css` should always override the styles of `gresource`. Otherwise, the `gresource` styles will be used. That means, in your system, just replacing `border: none` to `border-color: transparent` doesn't change the border-width.

So I think it will work if you replace `border: none` to `border: transparent` as @kpuljek did.

**Comment by isantop** [comment]
I modified the SCSS and reinstalled from there. I'm not seeing any difference either way, so the top-bar overview styling doesn't appear to be different enough to warrant having a separate style anyway.

**Comment by nana-4** [comment]
@isantop Hmm, I understand. Sorry for bothering you.
