### ISSUE TITLE
Pad headerbar separators

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/gtk-theme#94]
I figured out part of why elementary Mail looks more cluttered in Pop! than elementary OS: headerbar separators. In the elementary stylesheet, we pad the separators pretty significantly even though they don't draw an actual line on the headerbar. This means elementary apps have a standard "spacer" type widget by just using a separator, and the stylesheet takes care of the rest.

We should see if that'd work in Pop! as well; I like that we don't draw the line for separators, but perhaps we can add some padding since app authors are explicitly expecting _some_ sort of visual separation/grouping of headerbar items.

I'm currently on the latest commit of the version-3 branch.

**Comment by cassidyjames** [comment]
For reference:

## Pop!
![mail-pop](https://user-images.githubusercontent.com/611168/33681860-06c60d20-da83-11e7-8312-d121f0d59b20.png)

## Adwaita
![mail-adwaita](https://user-images.githubusercontent.com/611168/33681866-08dec548-da83-11e7-8a94-a90cd10baf28.png)

## elementary
![mail-elementary](https://user-images.githubusercontent.com/611168/33681868-0a14214c-da83-11e7-8a5d-ecd2c135795a.png)

Adwaita draws a line which is subtle but provides some separation. elementary draws padding which also provides separation. Pop! does neither.

**Comment by isantop** [comment]
This appears to be fixed in Pop 3.1, and is also included in v4
