### ISSUE TITLE
Unable to use change_color.sh in 3.0.0-b1

### ISSUE THREAD

**Issue by jlacroix82** [pop-os/gtk-theme#95]
The change_color.sh script doesn't seem to work for me. I'm testing with 3.0.0-b1. See the output below:

./change_color.sh -o my-test-theme <(echo -e BG=d8d8d8\nFG=101010\nMENU_BG=3c3c3c\nMENU_FG=e6e6e6\nSEL_BG=ad7fa8\nSEL_FG=ffffff\nTXT_BG=ffffff\nTXT_FG=1a1a1a\nBTN_BG=f5f5f5\nBTN_FG=111111\n

./change_color.sh: line 82: SEL_BG: unbound variable

**Comment by isantop** [comment]
I should probably remove that script, it's a leftover from Materia and doesn't work with Pop at all.

**Comment by isantop** [comment]
For modifying the color of the theme, for now you'll need to change the colors listed in the following files:
`src/xfwm4/recolor-assets.sh`
`src/gtk-2.0/recolor-assets.sh`
`src/gtk-3.0/gtk-common/recolor-assets.sh`
`src/gnome-shell/common/sass/_colors.scss`
`src/gtk-3.0/3.22/sass/_colors.scss`

For the two .scss files, it's recommended to add your color definitions to the corresponding component's `_color-palatte.scss` file and reference the new definitions in `_colors.scss`. This will ensure things are properly updated throughout the theme and that you don't end up with conflicts in other files.
