### ISSUE TITLE
Disabled buggons not discernible

### ISSUE THREAD

**Issue by luispabon** [pop-os/gtk-theme#97]
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
```
libgtk-3-0:
  Installed: 3.22.25-0ubuntu0.1
  Candidate: 3.22.25-0ubuntu0.1
  Version table:
 *** 3.22.25-0ubuntu0.1 500
        500 http://gb.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.22.24-0ubuntu1 500
        500 http://gb.archive.ubuntu.com/ubuntu artful/main amd64 Packages
```
 * Desktop environment 
Unity 7
 * Pop version - (run ```head -n 3 /usr/share/themes/Pop/gtk-3.22/gtk.css```)
```
Pop!_GTK+ Version 2.2.3r0
```

Disabled buttons on the theme are styled the same way as actionable buttons. Here's an example in Numix:

![image](https://user-images.githubusercontent.com/6388823/33714663-add61564-db47-11e7-9d6d-e513601fedb8.png)

Here's on Pop:

![image](https://user-images.githubusercontent.com/6388823/33714807-38ab5618-db48-11e7-9cea-de160ed815f0.png)
![image](https://user-images.githubusercontent.com/6388823/33714820-46777038-db48-11e7-8d05-55fd85253515.png)
![image](https://user-images.githubusercontent.com/6388823/33714832-54dbc37c-db48-11e7-8975-b7e86b38f26a.png)

**Comment by isantop** [comment]
I can't seem to replicate this on my end. Looking at the same same set of buttons on my system, the caibrate button is properly indicated as disabled. 
![screenshot from 2017-12-07 09-19-12](https://user-images.githubusercontent.com/5883565/33725945-ea9fa09e-db30-11e7-8aec-e81413984347.png)

**Comment by isantop** [comment]
Closing for now due to lack of response from reporter.
